var request = require('request');

	var ru = [{
		"head": {
			"title": "Art Challenge – Игра на знание популярных художников",
			"description": "Попробуйте отгадать 10 художников подряд и победить своих друзей!"
		},
		"desc": {
			"what": "Что здесь происходит?",
			"what-desc": "Вам предлагается развлечь себя игрой на знание истории изобразительного искусства.",
			"how": "Как это работает?",
			"how-desc": "Нужно отгадывать авторов картин.<br>Побеждают те господа, которые смогут отгадать 10 картин подряд.",
			"what-good": "Какая от этого польза?",
			"what-good-desc": "Играйте в свободное время, и очень скоро Вы без труда будете отличать Клода Моне<br>от Эдуарда Мане с первого взгляда, и уж точно от Альфреда Сислея :)",
			"how-help": "Нравится Art Challenge?",
			"how-help-desc": "Если Вам понравился сайт, будьте так любезны, расскажите о нём друзьям:",
			"settings": "Настройки",
			"lang": "Язык",
			"swear": "Шуточки",
      "emoji": "Смайлики",
			"swear-on": "Вкл.",
			"swear-off": "Выкл.",
			"subscribe": "Подписывайтесь на новости",
			"press": "Пресса о нас:",
			"menu": "Меню",
			"menuSinglePlayer": "Одиночная игра",
			"menuDuel": "Дуэль с другом",
			"menuTournament": "Лучшие игроки",
			"setCurrent": "Текущая коллекция",
 			"setChooseDesc": "Выбор коллекции",
			"setChooseBtn": "Играть",
			"setPlayingNow": "Вы играете в эту коллекцию",
			"statsTitle": "Статистика",
			"statsAnswersByDays": "Мои ответы по дням",
			"statsNoDataText": "Вы слишком мало играли в коллекцию <b>__setName__</b>, поиграйте в нее минимум два дня и тут появится график ваших ответов.",
			"statsCollectionKnow": "Мои знания коллекций",
			"statsLastAnswers": "Мои последние ответы",
			"statsPainting": "Картина",
			"statsYourAnswer": "Вы ответили",
      "statsMyProfile": "Мой профиль",
      "statsYourBestPainters": "Самые узнаваемые художники",
      "statsYourWorstPainters": "Самые неузнаваемые художники",
			"loginTitle": "Регистрация",
			"loginUnregisteredPlayer": "Неизвестный игрок",
			"loginClickToRegister": "Нажмите, чтобы войти",
			"loginName": "Имя",
			"loginNameExample": "Например, Иван Петров",
			"loginEmail": "E-mail",
			"loginEmailExample": "Например, ivan@mail.ru",
			"loginBtnRegister": "Зарегистрироваться",
			"loginRegisterDesc": "Регистрация позволит вам участвовать в турнире, а так же сохранять статистику своих игр",
			"loginLoginForRegistered" : "Уже зарегистрированы?",
			"loginLoginForRegisteredHint": "Просто введите свой E-mail, который использовали при регистрации",
			"loginBtnLogin": "Войти",
			"loginMessageSuccessRegister": "Вы успешно зарегистрированы!",
			"loginMessageSuccessLogin": "Вы успешно вошли!",
			"loginSuccessEmailText": "__username__, спасибо Вам за регистрацию в Art Challenge!<br>Теперь вы сможете участвовать в турнире и отслеживать статистику своих ответов в игре.<br>По любым вопросам пишите нам на info@artchallenge.ru.<br>Если хотите следить за новостями из мира культуры, то подписывайте на нас в социальных сетях:<br>ВКонтакте: http://vk.com/art.challenge<br>Facebook: http://facebook.com/artchallenge.ru<br><br>Искренне Ваши, команда Art Challenge<br>Рубен и Анна.",
			"loginMessageErrorEmail": "Введите корректный E-mail",
			"loginMessageError": "Введите имя пользователя и корректный E-mail",
			"loginMessageErrorDuplicate": "Ошибка регистрации: Пользователь с такими E-mail уже существует",
			"loginMessageErrorForbiddenName": "Ошибка регистрации: Запрещенное имя пользователя",
			"loginMessageErrorServer": "Ошибка регистрации: Сервер не доступен, попробуйте позже",
      "errorOffline": "Отсутствует подключение к интернету",
      "swipeCollections": "ВЫБЕРИТЕ КОЛЛЕКЦИЮ",
      "swipePictures": "ЛИСТАЙТЕ КАРТИНЫ",
      "yourPlace": "Вы на __place__ месте",
      "highQualityPictures": "Высокое качество",
      "highQualityPicturesDesc": "Картинки высокого качества будут загружаться из интернета",
      "picturesInRow": "подряд",
      "reportError": "Обнаружили ошибку?",
      "reportEmail": "Обязательно сообщите нам на report@artchallenge.ru",
      "subscribeNoSpam": "Никакого спама. Только замечательные новости из мира искусства.",
      "about": "Об игре",
      "aboutSponsors": "Art Challenge создан Рубеном Бабаевым и Анной Плоткиной благодаря поддержке наших дорогих меценатов:",
      "gameVersion": "Версия игры",
      "exit": "Выход"

		},
		"message": {
			"right": "Верно!",
			"right-desc": "Вы отгадали __count__ картину",
			"wrong": "Неверно!",
			"wrong-desc": "Это же",
			"years": "Годы жизни",
			"nationality": "Национальность",
			"genre": "Жанр",
			"learn-more": "Узнать больше",
			"winner": "Поздравляем!",
			"winner-desc": "Коллекция <strong>__setName__</strong> пройдена!",
			"winner-desc-old": "Вы великолепно разбираетесь в искусстве! 10 из 10 – это лучше, чем 82% людей, сыгравших в эту игру!",
			"share": "Вы можете рассказать о победе в социальных сетях:",
      "winnerMobile": "Вы великолепно разбираетесь в коллекции",
      "shareOrTournament": "Расскажите о победе своим друзьям и примите участие в турнире на самую длинную серию правильных ответов:",
      "shareWithFriends": "Рассказать друзьям",
      "playTournament": "Турнир",
      "loading": "Загрузка",
      "closeWinTitle": "Начать новую игру",
      "closeWinMessage": "Вы хотите закрыть это окно и начать новую игру?"
		},
		"badPhrases": {
			"1": "Да Вы обезумели!",
			"2": "Ну как не стыдно?",
			"3": "Вам нездоровится?",
			"4": "Что за нелепость?",
			"5": "Займитесь самообразованием!",
			"6": "Как Вы могли?..",
			"7": "Нет, нет и нет!",
			"8": "Одумайтесь!",
			"9": "А если подумать?",
			"10": "Какого чёрта?!",
			"11": "Бескультурье!",
			"12": "Коллега!"
		},
		"goodPhrases": {
			"1": "Так держать!",
			"2": "Верно!",
			"3": "Браво!",
			"4": "Отлично!",
			"5": "Великолепно!",
			"6": "Замечательно!",
			"7": "Здорово!",
			"8": "Совершенно верно!",
			"9": "Абсолютно верно!",
			"10": "Точно!",
			"11": "Правильно!",
			"12": "Это бесспорно!",
			"13": "Действительно так!",
			"14": "Чудесно!",
			"15": "Класс!",
			"16": "Блеск!",
			"17": "Блестяще!",
			"18": "Восхитительно!",
			"19": "Поразительно!",
			"20": "Наша школа!"
		},
		"shares": {
			"title": "Господа, я отлично разбираюсь в искусстве!",
			"description": "Попробуйте отгадать 10 художников подряд и посоревноваться со мной!",
			"caption": "Art Challenge – Игра на знание популярных художников"
		},
		"footer": {
			"created": "Сайт создан",
			"ruben": "Рубеном",
			"ruben-full": "Рубен Бабаев",
			"and": "и",
			"anna": "Анной",
			"anna-full": "Анна Плоткина",
			"year": "в 2014 году",
			"vk": "ВКонтакте",
			"other-projects": "Другие наши проекты"
		},
		"painters": {
			"1": "Амедео Модильяни",
			"2": "Анри Лебаск",
			"3": "Архип Куинджи",
			"4": "Василий Кандинский",
			"5": "Василий Суриков",
			"6": "Виктор Борисов-Мусатов",
			"7": "Диего Ривера",
			"8": "Иван Шишкин",
			"9": "Клод Моне",
			"10": "Константин Юон",
			"11": "Николай Рерих",
			"12": "Орест Кипренский",
			"13": "Кузьма Петров-Водкин",
			"14": "Рене Магритт",
			"15": "Сальвадор Дали",
			"16": "Сергей Виноградов",
			"17": "Эдуард Мане",
			"18": "Эндрю Уайет",
			"19": "Андрей Рублёв",
			"20": "Виктор Васнецов",
			"21": "Винсент Ван Гог",
			"22": "Густав Климт",
			"23": "Иван Айвазовский",
			"24": "Иероним Босх",
			"25": "Илья Репин",
			"26": "Казимир Малевич",
			"27": "Михаил Врубель",
			"28": "Пабло Пикассо",
			"29": "Питер Рубенс",
			"30": "Пьер Огюст Ренуар",
			"31": "Феофан Грек",
			"32": "Франсиско Гойя",
			"33": "Фрида Кало",
			"34": "Эль Греко",
			"35": "Альбрехт Дюрер",
			"36": "Альфред Сислей",
			"37": "Борис Кустодиев",
			"38": "Карл Брюллов",
			"39": "Питер Брейгель",
			"40": "Марк Шагал",
			"41": "Джотто ди Бондоне",
			"42": "Сандро Боттичелли",
			"43": "Караваджо",
			"44": "Зинаида Серебрякова",
			"45": "Леонардо да Винчи",
			"46": "Диего Веласкес",
			"47": "Василий Верещагин",
			"48": "Исаак Левитан",
			"49": "Анри Матисс",
			"50": "Ян ван Эйк",
			"51": "Джон Уотерхаус",
			"52": "Эгон Шиле",
			"53": "Эдгар Дега",
			"54": "Рембрандт",
			"55": "Тициан",
			"56": "Альфонс Муха",
			"57": "Анри Тулуз-Лотрек",
			"58": "Гюстав Курбе",
			"59": "Данте Габриэль Россетти",
			"60": "Джон Сингер Сарджент",
			"61": "Камиль Писсарро",
			"62": "Уильям Тернер",
			"63": "Эдвард Мунк",
			"64": "Антуан Ватто",
			"65": "Вильям Бугро",
			"66": "Джон Констебл",
			"67": "Джон Эверетт Милле",
			"68": "Питер де Хох",
			"69": "Поль Сезанн",
			"70": "Теодор Жерико",
			"71": "Томас Гейнсборо",
			"72": "Уильям Блейк",
			"73": "Эжен Делакруа",
			"74": "Ян Вермеер",
			"75": "Анри Руссо",
			"76": "Владимир Боровиковский",
			"77": "Жорж-Пьер Сёра",
			"78": "Люсьен Фрейд",
			"79": "Пауль Клее",
			"80": "Пит Мондриан",
			"81": "Павел Филонов",
			"82": "Жоан Миро",
			"83": "Энди Уорхол",
			"84": "Валентин Серов",
			"85": "Алексей Харламов",
			"86": "Василий Тропинин",
			"87": "Фра Анджелико",
			"88": "Эдвард Бёрн-Джонс",
			"89": "Мартин Шонгауэр",
			"90": "Рогир ван дер Вейден",
			"91": "Джованни ди Паоло",
			"92": "Ханс Бальдунг",
			"93": "Гюстав Моро",
			"94": "Поль Гоген",
			"95": "Рафаэль Санти",
			"96": "Поль Синьяк",
			"97": "Никола Пуссен",
			"98": "Ганс Гольбейн",
			"99": "Уильям Холман Хант",
			"100": "Альбрехт Альтдорфер",
			"101": "Антонелло да Мессина",
			"102": "Артур Хьюз",
			"103": "Бенуа Александр",
			"104": "Ганс Мемлинг",
			"105": "Александр Дейнека",
			"106": "Джорджоне",
			"107": "Александр Иванов",
			"108": "Корреджо",
			"109": "Дмитрий Левицкий",
			"110": "Лукас ван Лейден",
			"111": "Лукас Кранах",
			"112": "Микеланджело",
			"113": "Николай Ге",
			"114": "Робер Кампен",
			"115": "Фёдор Рокотов",
			"116": "Рокуэлл Кент",
			"117": "Мартирос Сарьян",
			"118": "Джексон Поллок"
		},
		"nation": {
			"Russian": "Русский",
			"Armenian": "Армянин",
			"Italian": "Итальянец",
			"French": "Француз",
			"Mexican": "Мексиканец",
			"Belgian": "Бельгиец",
			"Spanish": "Испанец",
			"American": "Американец",
			"Dutch": "Голландец",
			"Austrian": "Австриец",
			"Flemish": "Фламандец",
			"German": "Немец",
			"British": "Англичанин",
			"Jewish": "Еврей",
			"Belarusian": "Белорус",
			"Czech": "Чех",
			"Greek": "Грек",
			"Norwegian": "Норвежец",
			"Ukrainian": "Украинец",
			"Swiss": "Швед"
		},
		"genre": {
			"Romanticism": "Романтизм",
			"Expressionism": "Экспрессионизм",
			"Impressionism": "Импрессионизм",
			"Realism": "Реализм",
			"Abstractionism": "Абстракционизм",
			"Symbolism": "Символизм",
			"Muralism": "Мурализм",
			"Social Realism": "Социальный Реализм",
			"Surrealism": "Сюрреализм",
			"Byzantine Art": "Византийское Искусство",
			"Post-Impressionism": "Постимпрессионизм",
			"Art Nouveau": "Ар Нуво",
			"Northern Renaissance": "Северное Возрождение",
			"Suprematism": "Супрематизм",
			"Cubism": "Кубизм",
			"Baroque": "Барокко",
			"Iconography": "Иконопись",
			"Primitivism": "Примитивизм",
			"Mannerism": "Маньеризм",
			"Neoclassicism": "Неоклассицизм",
			"Proto Renaissance": "Проторенессанс",
			"Early Renaissance": "Раннее Возрождение",
			"Art Deco": "Ар-деко",
			"High Renaissance": "Высокое Возрождение",
			"Aestheticism": "Эстетизм",
			"Analytical Realism": "Аналитический реализм",
			"Neoplasticism": "Неопластицизм",
			"Rococo": "Рококо",
			"Pop Art": "Поп-арт",
			"Socialist Realism": "Социалистический реализм",
			"Academic Art": "Академизм",
			"Abstract Expressionism": "Абстрактный экспрессионизм"
		},
		"sets": {
			"basicSet": "Популярные художники",
			"basicSet-desc": "Коллекция, состоящая из картин самых известных художников",
			"basicSet-count": "50 художников, 8 450 картин",
			"renaissanceSet": "Эпоха Возрождения",
			"renaissanceSet-desc": "От Северного Возрождения и Проторенессанса к полотнам Высокого Возрождения",
			"renaissanceSet-count": "24 художника, 2 783 картины",
			"impressionismSet" : "Импрессионизм и Постимпрессионизм",
			"impressionismSet-desc" : "Работы художников-импрессионистов и постимпрессионистов",
			"impressionismSet-count": "18 художников, 4 231 картина",
			"realismSet": "Художники-реалисты",
			"realismSet-desc": "Коллекция полотен художников-реалистов",
			"realismSet-count": "12 художников, 2 083 картины",
			"russianSet": "Русские художники",
			"russianSet-desc": "Всех времен и разных направлений",
			"russianSet-count": "33 художника, 5 140 картин",
			"frenchSet": "Французские художники",
			"frenchSet-desc": "Коллекция французских художников",
			"frenchSet-count": "22 художника, 3 758 картин",
			"allSet": "Полная коллекция",
			"allSet-desc": "Все художники, чьи картины добавлены в игру - для более опытных игроков",
			"allSet-count": "118 художников, 17 695 картин"
		}
	}];

	var en = [{
		"head": {
			"title": "Art Challenge – A Quiz Game of Famous Painters",
			"description": "Try to guess 10 painters in a row and beat your friends!"
		},
		"desc": {
			"what": "What's going on here?",
			"what-desc": "We offer you to have some fun by playing the art history game!",
			"how": "How does it work?",
			"how-desc": "You need to guess the artists who made famous paintings.<br>You win if you manage to guess 10 painters in a row.",
			"what-good": "What’s the use of it?",
			"what-good-desc": "Play in your free time and very soon you’ll be able to tell Claude Monet from Edouard Manet at a glance, let alone Alfred Sisley :)",
			"how-help": "How can I help?",
			"how-help-desc": "If you like this site, could you be so kind to share it with your friends?",
			"settings": "Settings",
			"lang": "Language",
			"swear": "Jokes",
      "emoji": "Emoticons",
			"swear-on": "On",
			"swear-off": "Off",
			"subscribe": "Subscribe for news:",
			"press": "Press about us:",
			"menu": "Menu",
			"menuSinglePlayer": "Single Player",
			"menuDuel": "Duel with Friend",
			"menuTournament": "Best Players",
			"setCurrent": "Collection",
 			"setChooseDesc": "Choose a collection",
			"setChooseBtn": "Play Now",
			"setPlayingNow": "You're now playing in this collection",
			"statsTitle": "Statistics",
			"statsAnswersByDays": "My progress by days",
			"statsNoDataText": "Too few games in the collection of <b>__setName__</b>, play it a few days and we will show a graph with your answers here.",
			"statsCollectionKnow": "My knowledge of collections",
			"statsLastAnswers": "My last answers",
			"statsPainting": "Painting",
			"statsYourAnswer": "Your answer",
      "statsMyProfile": "My profile",
      "statsYourBestPainters": "The most recognisable painters",
      "statsYourWorstPainters": "The most unrecognisable painters",
			"loginTitle": "Register",
			"loginUnregisteredPlayer": "Unregistered player",
			"loginClickToRegister": "Click to register",
			"loginName": "Name",
			"loginNameExample": "For example, John Doe",
			"loginEmail": "E-mail",
			"loginEmailExample": "For example, johndoe@gmail.com",
			"loginBtnRegister": "Register",
			"loginRegisterDesc": "Registration will allow you to participate in tournament and keep the statistics of your games",
			"loginLoginForRegistered" : "Already registered?",
			"loginLoginForRegisteredHint": "Enter your E-mail, which was used during registration",
			"loginBtnLogin": "Login",
			"loginMessageSuccessRegister": "You have registered successfully!",
			"loginMessageSuccessLogin": "You have successfully logged!",
			"loginSuccessEmailText": "__username__, thank you for registering in Art Challenge!<br>Now you can take part in the tournament and monitor the statistics of your games.<br>For any questions please contact us at info@artchallenge.ru.<br>If you want to follow the news from the world of culture, then follow us in social networks:<br>VKontakte: http://vk.com/art.challenge<br>Facebook: http://facebook.com/artchallenge.ru<br><br>Sincerely, Art Challenge Team<br>Ruben and Anna.",
			"loginMessageErrorEmail": "Enter a valid E-mail",
			"loginMessageError": "Enter your user name and valid E-mail",
			"loginMessageErrorDuplicate": "Registration error: User with such E-mail address already exists",
			"loginMessageErrorForbiddenName": "Registration error: Forbidden username",
			"loginMessageErrorServer": "Registration error: The server is not available, try again later",
      "errorOffline": "No internet connection",
      "swipeCollections": "CHOOSE A COLLECTION",
      "swipePictures": "SWIPE PAINTINGS",
      "yourPlace": "__place__ place",
      "highQualityPictures": "High quality",
      "highQualityPicturesDesc": "High quality pictures will be downloaded from internet",
      "picturesInRow": "in a row",
      "reportError": "Have you found an error?",
      "reportEmail": "Please let us know at report@artchallenge.ru",
      "subscribeNoSpam": "No spam. Only marvellous news about the world of art.",
      "about": "About the game",
      "aboutSponsors": "Art Challenge was created by Ruben Babaev and Anna Plotkina thanks to the support of our dear patrons:",
      "gameVersion": "Game's version",
      "exit": "Log out"
		},
		"message": {
			"right": "You got it right!",
			"right-desc": "The painting __count__ is done",
			"wrong": "Wrong!",
			"wrong-desc": "That's",
			"years": "Years",
			"nationality": "Nationality",
			"genre": "Genre",
			"learn-more": "Learn more",
			"winner": "Congratulations!",
			"winner-desc": "Collection of <strong>__setName__</strong> passed!",
			"winner-desc-old": "You are really good at Art!<br>10 out of 10 – it is better than 82% of people who has played this game!",
			"share": "You can share your victory with friends:",
      "winnerMobile": "You are really good at collection",
      "shareOrTournament": "Tell your friends about the victory and take part in the tournament for the longest series of correct answers:",
      "shareWithFriends": "Share with friends",
      "playTournament": "Tournament",
      "loading": "Loading",
      "closeWinTitle": "Start a new game",
      "closeWinMessage": "Do you wish to close this window and start a new game?"
		},
		"badPhrases": {
			"1": "You are nuts!",
			"2": "Damn..., huh?",
			"3": "Shame on you, man!",
			"4": "Are you unwell?!",
			"5": "This is ridiculous!",
			"6": "What`s the nonsense?!",
			"7": "You’s better upgrade yourself!",
			"8": "No, no and no!",
			"9": "Think better!",
			"10": "Sorry, it`s wrong.",
			"11": "What`s the hell?",
			"12": "God blind me!.."
		},
		"goodPhrases": {
			"1": "You got it right!",
			"2": "Keep it up!",
			"3": "It's true!",
			"4": "Bravo!",
			"5": "Excellent!",
			"6": "Great!",
			"7": "Wonderful!",
			"8": "Wow!",
			"9": "Quite right!",
			"10": "Absolutely!",
			"11": "Exactly!",
			"12": "That's right!",
			"13": "It is indisputable!",
			"14": "Indeed so!",
			"15": "Wonderful!",
			"16": "Brilliant!",
			"17": "It's amazing!",
			"18": "Delightfully!",
			"19": "Strikingly!",
			"20": "Yeah, dude!"
		},
		"shares": {
			"title": "Ladies and Gentlemen, I am really good at Art!",
			"description": "Try to guess 10 painters in a row and beat your friends!",
			"caption": "Art Challenge – A Quiz Game of Famous Painters"
		},
		"footer": {
			"created": "Created by",
			"ruben": "Ruben",
			"ruben-full": "Ruben Babaev",
			"and": "and",
			"anna": "Anna",
			"anna-full": "Anna Plotkina",
			"year": "in 2014",
			"vk": "VKontakte",
			"other-projects": "Our other projects"
		},
		"painters": {
			"1": "Amedeo Modigliani",
			"2": "Henri Lebasque",
			"3": "Arkhip Kuinji",
			"4": "Vasiliy Kandinskiy",
			"5": "Vasily Surikov",
			"6": "Victor Borisov-Musatov",
			"7": "Diego Rivera",
			"8": "Ivan Shishkin",
			"9": "Claude Monet",
			"10": "Konstantin Yuon",
			"11": "Nicholas Roerich",
			"12": "Orest Kiprensky",
			"13": "Kuzma Petrov-Vodkin",
			"14": "René Magritte",
			"15": "Salvador Dalí",
			"16": "Sergei Vinogradov",
			"17": "Edouard Manet",
			"18": "Andrew Wyeth",
			"19": "Andrei Rublev",
			"20": "Viktor Vasnetsov",
			"21": "Vincent Willem van Gogh",
			"22": "Gustav Klimt",
			"23": "Ivan Aivazovsky",
			"24": "Hieronymus Bosch",
			"25": "Ilya Repin",
			"26": "Kazimir Malevich",
			"27": "Mikhail Vrubel",
			"28": "Pablo Picasso",
			"29": "Peter Paul Rubens",
			"30": "Pierre-Auguste Renoir",
			"31": "Theophanes the Greek",
			"32": "Francisco de Goya",
			"33": "Frida Kahlo",
			"34": "El Greco",
			"35": "Albrecht Dürer",
			"36": "Alfred Sisley",
			"37": "Boris Kustodiev",
			"38": "Karl Bryullov",
			"39": "Pieter Bruegel",
			"40": "Marc Chagall",
			"41": "Giotto di Bondone",
			"42": "Sandro Botticelli",
			"43": "Caravaggio",
			"44": "Zinaida Serebriakova",
			"45": "Leonardo da Vinci",
			"46": "Diego Velázquez",
			"47": "Vasily Vereshchagin",
			"48": "Isaac Levitan",
			"49": "Henri Matisse",
			"50": "Jan van Eyck",
			"51": "John Waterhouse",
			"52": "Egon Schiele",
			"53": "Edgar Degas",
			"54": "Rembrandt",
			"55": "Titian",
			"56": "Alphonse Mucha",
			"57": "Henri de Toulouse-Lautrec",
			"58": "Gustave Courbet",
			"59": "Dante Gabriel Rossetti",
			"60": "John Singer Sargent",
			"61": "Camille Pissarro",
			"62": "William Turner",
			"63": "Edvard Munch",
			"64": "Antoine Watteau",
			"65": "William-Adolphe Bouguereau",
			"66": "John Constable",
			"67": "John Everett Millais",
			"68": "Pieter de Hooch",
			"69": "Paul Cézanne",
			"70": "Theodore Gericault",
			"71": "Thomas Gainsborough",
			"72": "William Blake",
			"73": "Eugène Delacroix",
			"74": "Johannes Vermeer",
			"75": "Henri Rousseau",
			"76": "Vladimir Borovikovsky",
			"77": "Georges Seurat",
			"78": "Lucian Freud",
			"79": "Paul Klee",
			"80": "Piet Mondrian",
			"81": "Pavel Filonov",
			"82": "Joan Miro",
			"83": "Andy Warhol",
			"84": "Valentin Serov",
			"85": "Alexei Harlamov",
			"86": "Vasily Tropinin",
			"87": "Fra Angelico",
			"88": "Edward Burne-Jones",
			"89": "Martin Schongauer",
			"90": "Rogier van der Weyden",
			"91": "Giovanni di Paolo",
			"92": "Hans Baldung",
			"93": "Gustave Moreau",
			"94": "Paul Gauguin",
			"95": "Raphael Sanzio",
			"96": "Paul Signac",
			"97": "Nicolas Poussin",
			"98": "Hans Holbein",
			"99": "William Holman Hunt",
			"100": "Albrecht Altdorfer",
			"101": "Antonello da Messina",
			"102": "Arthur Hughes",
			"103": "Alexandre Benois",
			"104": "Hans Memling",
			"105": "Aleksandr Deyneka",
			"106": "Giorgione",
			"107": "Alexander Ivanov",
			"108": "Correggio",
			"109": "Dmitry Levitzky",
			"110": "Lucas van Leyden",
			"111": "Lucas Cranach the Elder",
			"112": "Michelangelo Buonarroti ",
			"113": "Nikolai Ge",
			"114": "Robert Campin",
			"115": "Fyodor Rokotov",
			"116": "Rockwell Kent",
			"117": "Martiros Saryan",
			"118": "Jackson Pollock"
		},
		"nation": {
			"Russian": "Russian",
			"Armenian": "Armenian",
			"Italian": "Italian",
			"French": "French",
			"Mexican": "Mexican",
			"Belgian": "Belgian",
			"Spanish": "Spanish",
			"American": "American",
			"Dutch": "Dutch",
			"Austrian": "Austrian",
			"Flemish": "Flemish",
			"German": "German",
			"British": "British",
			"Jewish": "Jewish",
			"Belarusian": "Belarusian",
			"Czech": "Czech",
			"Greek": "Greek",
			"Norwegian": "Norwegian",
			"Ukrainian": "Ukrainian",
			"Swiss": "Swiss"
		},
		"genre": {
			"Romanticism": "Romanticism",
			"Expressionism": "Expressionism",
			"Impressionism": "Impressionism",
			"Realism": "Realism",
			"Abstractionism": "Abstractionism",
			"Symbolism": "Symbolism",
			"Muralism": "Muralism",
			"Social Realism": "Social Realism",
			"Surrealism": "Surrealism",
			"Byzantine Art": "Byzantine Art",
			"Post-Impressionism": "Post-Impressionism",
			"Art Nouveau": "Art Nouveau",
			"Northern Renaissance": "Northern Renaissance",
			"Suprematism": "Suprematism",
			"Cubism": "Cubism",
			"Baroque": "Baroque",
			"Iconography": "Iconography",
			"Primitivism": "Primitivism",
			"Mannerism": "Mannerism",
			"Neoclassicism": "Neoclassicism",
			"Proto Renaissance": "Proto Renaissance",
			"Early Renaissance": "Early Renaissance",
			"Art Deco": "Art Deco",
			"High Renaissance": "High Renaissance",
			"Aestheticism": "Aestheticism",
			"Analytical Realism": "Analytical Realism",
			"Neoplasticism": "Neoplasticism",
			"Rococo": "Rococo",
			"Pop Art": "Pop Art",
			"Socialist Realism": "Socialist Realism",
			"Academic Art": "Academic Art",
			"Abstract Expressionism": "Abstract Expressionism"
		},
		"sets": {
			"basicSet": "Popular painters",
			"basicSet-desc": "Collection of the most famous painters",
			"basicSet-count": "50 painters, 8 450 paintings",
			"renaissanceSet": "The Renaissance",
			"renaissanceSet-desc": "From Northern Renaissance and Early Renaissance to High Renaissance paintings",
			"renaissanceSet-count": "24 painters, 2 783 paintings",
			"impressionismSet" : "Impressionism and Post-Impressionism",
			"impressionismSet-desc" : "Works of the Impressionists and Post- Impressionists",
			"impressionismSet-count": "18 painters, 4 231 paintings",
			"realismSet": "Realism painters",
			"realismSet-desc": "The realism painters collection",
			"realismSet-count": "12 painters, 2 083 paintings",
			"russianSet": "Russian painters",
			"russianSet-desc": "Painters of different periods and art movements",
			"russianSet-count": "33 painters, 5 140 paintings",
			"frenchSet": "French painters",
			"frenchSet-desc": "The French collection",
			"frenchSet-count": "22 painters, 3 758 paintings",
			"allSet": "Full collection",
			"allSet-desc": "All the painters included in this quiz - for more proficient users",
			"allSet-count": "118 painters, 17 695 paintings"
		}
	}];

	var de = [{
		"head": {
			"title": "Art Challenge – das Spiel von berühmten Kunstmalern",
			"description": "Versuchen Sie zu 10 Kunstmaler nacheinander zu erraten und Ihre Freunde zu besiegen"
		},
		"desc": {
			"what": "Was ist überhaupt loss hier?",
			"what-desc": "Es wird angeboten sich mit dem Spiel zu Kenntnissen in Gustgeschichte zu unterhalten.",
			"how": "Wie funktioniert es?",
			"how-desc": "Man muss die Künstlernamen zu erraten.<br> Gewinnen die Herrschaften, die 10 Gemäldeautoren nacheinander erraten können.",
			"what-good": "Was bringt es?",
			"what-good-desc": "Spielen Sie in Ihrer Freizeit und in der kurze Zeit gelingt es Ihnen vom ersten Blick Claude Monet von Edouard Manet und sicher von Alfred Sisley zu unterscheiden.",
			"how-help": "Gefällt Ihnen ArtChallenge?",
			"how-help-desc": "Wenn diese Website Ihnen gefällt, seien Sie so gut und erzählen Sie darüber Ihren Freunden.",
			"settings": "Einstellungen",
			"lang": "Sprache",
			"swear": "Schimpfworter",
      "emoji": "Emoticons",
			"swear-on": "Ein",
			"swear-off": "Aus",
			"subscribe": "Abonnieren Sie die Neuigkeiten:",
			"press": "Presse über uns:",
			"menu": "Menu",
			"menuSinglePlayer": "Einzelspieler",
			"menuDuel": "Duell mit Freund",
			"menuTournament": "Beste Spieler",
			"setCurrent": "aktuelle Kollektion",
 			"setChooseDesc": "Sammlungsauswahl",
			"setChooseBtn": "Spielen",
			"setPlayingNow": "Sie benutzen diese Sammlung",
			"statsTitle": "Statistik",
			"statsAnswersByDays": "Mein täglicher Progress",
			"statsNoDataText": "Sie haben zu wenig in dieser Sammlung gespiellt <b>__setName__</b>, spielen Sie es mindestens zwei Tage und hier wird Ihre Erfolgsstatistik erscheinen.",
			"statsCollectionKnow": "Meine Sammlungkenntnisse",
			"statsLastAnswers": "Meine letzte Antworten",
			"statsPainting": "Gemälde",
			"statsYourAnswer": "Ihre Antwort",
      "statsMyProfile": "Mein Profil",
      "statsYourBestPainters": "Die meist erkannbare Maler",
      "statsYourWorstPainters": "Die wenigst erkannbare Maler",
			"loginTitle": "Anmeldung",
			"loginUnregisteredPlayer": "Unbekannter Spieler",
			"loginClickToRegister": "Klicken Sie, zum einloggen",
			"loginName": "Name",
			"loginNameExample": "zum Beispiel, Max Mustermann",
			"loginEmail": "E-mail",
			"loginEmailExample": "zum Beispiel, mmustermann@gmail.com",
			"loginBtnRegister": "anmelden",
			"loginRegisterDesc": "mit der Anmeldung können Sie in einem Turnier teilnehmen sowie Statistik Ihrer Erfolge speichern",
			"loginLoginForRegistered" : "Schon registriert?",
			"loginLoginForRegisteredHint": "Geben Sie das E-mail, das bei der Anmeldung benutzt wurde.",
			"loginBtnLogin": "Einloggen",
			"loginMessageSuccessRegister": "Sie sind erfolgreich angemeldet!",
			"loginMessageSuccessLogin": "Sie sind erfolgreich eingeloggt!",
			"loginSuccessEmailText": "__username__, danke für Ihre Anmeldung in Art Challenge!<br> Jetzt können Sie in einem Turnier teilnehmen und Ihre Erfolgsstatistik  im Spiel verfolgen.<br>Bei allen Fragen schreiben Sie uns an  info@artchallenge.ru.<br>Wenn Sie die Nachrichten aus Kulturwelt folgen wollen, abbonieren Sie uns in Sozialen Netzwerken<br> VKontakte: http://vk.com/art.challenge<br>Facebook:  http://facebook.com/artchallenge.ru<br><br> mit freundlichen Grüßen, Art Challenge Team<br>Ruben and Anna.",
			"loginMessageErrorEmail": "Geben Sie das richtige E-Mail ein",
			"loginMessageError": "Geben Sie den richtigen Namen und das E-Mail ein",
			"loginMessageErrorDuplicate": "Anmeldung fehlgeschlagen: der Benutzer mit dieser E-Mail Adresse existiert bereits",
			"loginMessageErrorForbiddenName": "Anmeldung fehlgeschlagen: das verbotene Benutzername",
			"loginMessageErrorServer": "Anmeldung fehlgeschlagen: der Server ist nicht verfügbar, versuchen Sie es später noch Mal",
      "errorOffline": "Internetverbindung ist fehlgeschlagen",
      "swipeCollections": "Wählen Sie die Sammlung aus",
      "swipePictures": "Blättern Sie die Gemälde",
      "yourPlace": "Sie sind am __place__",
      "highQualityPictures": "hohe Auflösung",
      "highQualityPicturesDesc": "Bilder in hohe Auflösung werden vom Internet heruntergeladen",
      "picturesInRow": "nacheinander",
      "reportError": "Fehler gefunden?",
      "reportEmail": "Teilen Sie es uns bitte an report@artchallenge.ru mit",
      "subscribeNoSpam": "Kein Spam. Nur spannende Nachrichten über die Kunstwelt.",
      "about": "Über das Spiel",
      "aboutSponsors": "Art Challenge wurde von Ruben Babaev und Anna Plotkina gegründet dank der Unterstützung unseren Mäzenen:",
      "gameVersion": "Spielversion",
      "exit": "Ausloggen"
		},
		"message": {
			"right": "Richtig!",
			"right-desc": "Sie haben das __count__ Künstler erraten",
			"wrong": "Das schtimmt nicht!",
			"wrong-desc": "Das ist doch",
			"years": "Lebensjahre",
			"nationality": "Nationalität",
			"genre": "Genre",
			"learn-more": "Mehr erfahren",
			"winner": "Unsere Gratulationen",
			"winner-desc": "Sammlung <strong>__setName__</strong> ist bestanden!",
			"winner-desc-old": "Sie verstehen viel von Kunst<br>10 aus 10 das ist besser als 82% von Menschen, die bei diesem Spiel mitgemacht haben!",
			"share": "Sie können Ihre Erfolge in Sozialen Netzwerken teilen",
      "winnerMobile": "Sie sind perfekt in der Sammlung versiert",
      "shareOrTournament": "Erzählen Sie über das Sieg Ihren Freunden und nehmen Sie an einem Turnier zu der längste Serie der richtigen Antworten teil:",
      "shareWithFriends": "Teilen mit Freunden",
      "playTournament": "Turnier",
      "loading": "Laden",
      "closeWinTitle": "Neues Spiel anfangen",
      "closeWinMessage": "Wollen Sie dieses Fenster schließen und neues Spiel anfangen?"
		},
		"badPhrases": {
			"1": "Sie sind ja verrückt!",
			"2": "Schämen Sie sich!",
			"3": "Fühlen Sie sich nicht wohl?",
			"4": "So ein Unsinn!",
			"5": "Bilden Sie sich gründlicher",
			"6": "Wie konnten Sie so machen?",
			"7": "Nein, nein und wieder nein!",
			"8": "Besinnen Sie sich anders",
			"9": "Denken Sie noch mal nach!",
			"10": "Was zum Teufel?!",
			"11": "Barbarei!",
			"12": "Mensch!!"
		},
		"goodPhrases": {
			"1": "Weiter so!",
			"2": "Richtig!",
			"3": "Bravo!",
			"4": "Wunderbar!",
			"5": "Ausgezeichnet!",
			"6": "Großartig!",
			"7": "Prima!",
			"8": "Ganz richtig!",
			"9": "Absolut richtig!",
			"10": "Genau!",
			"11": "Gar keine Frage!",
			"12": "Tatsächlich!",
			"13": "Wunderbar!",
			"14": "Klasse!",
			"15": "glänzendes Können!",
			"16": "Glänzend!",
			"17": "Das ist ja scharmant!",
			"18": "Erstaunlich!",
			"19": "Gut gemacht!",
			"20": "Richtig!"
		},
		"shares": {
			"title": "Liebe Damen und Herren, ich kenne mich gut in Kunst aus!",
			"description": "Versuchen Sie zu 10 Kunstmaler nacheinander zu erraten und Ihre Freunde zu besiegen!",
			"caption": "Art Challenge – das Spiel von berühmten Kunstmalern"
		},
		"footer": {
			"created": "Die Webseite ist von",
			"ruben": "Ruben",
			"ruben-full": "Ruben Babaev",
			"and": "und",
			"anna": "Anna",
			"anna-full": "Anna Plotkina",
			"year": "2014 gestaltet",
			"vk": "VKontakte",
			"other-projects": "Die anderen Werke von uns"
		},
		"painters": {
			"1": "Amedeo Modigliani",
			"2": "Henri Lebasque",
			"3": "Archip Kuindschi",
			"4": "Wassily Kandinsky",
			"5": "Wassili Surikow",
			"6": "Victor Borisov-Musatov",
			"7": "Diego Rivera",
			"8": "Iwan Schischkin",
			"9": "Claude Monet",
			"10": "Konstantin Juon",
			"11": "Nicholas Roerich",
			"12": "Orest Kiprenski",
			"13": "Kusma Petrow-Wodkin",
			"14": "René Magritte",
			"15": "Salvador Dalí",
			"16": "Sergei Vinogradov",
			"17": "Édouard Manet",
			"18": "Andrew Wyeth",
			"19": "Andrei Rubljow",
			"20": "Wiktor Wasnezow",
			"21": "Vincent van Gogh",
			"22": "Gustav Klimt",
			"23": "Iwan Aiwasowski",
			"24": "Hieronymus Bosch",
			"25": "Ilja Repin",
			"26": "Kasimir Malewitsch",
			"27": "Michail Wrubel",
			"28": "Pablo Picasso",
			"29": "Peter Paul Rubens",
			"30": "Pierre-Auguste Renoir",
			"31": "Theophanes der Grieche",
			"32": "Francisco de Goya",
			"33": "Frida Kahlo",
			"34": "El Greco",
			"35": "Albrecht Dürer",
			"36": "Alfred Sisley",
			"37": "Boris Kustodijew",
			"38": "Karl Brjullow",
			"39": "Pieter Bruegel",
			"40": "Marc Chagall",
			"41": "Giotto di Bondone",
			"42": "Sandro Botticelli",
			"43": "Caravaggio",
			"44": "Sinaida Serebrjakowa",
			"45": "Leonardo da Vinci",
			"46": "Diego Velázquez",
			"47": "Wassili Wereschtschagin",
			"48": "Isaak Lewitan",
			"49": "Henri Matisse",
			"50": "Jan van Eyck",
			"51": "John Waterhouse",
			"52": "Egon Schiele",
			"53": "Edgar Degas",
			"54": "Rembrandt",
			"55": "Tizian",
			"56": "Alfons Mucha",
			"57": "Henri de Toulouse-Lautrec",
			"58": "Gustave Courbet",
			"59": "Dante Gabriel Rossetti",
			"60": "John Singer Sargent",
			"61": "Camille Pissarro",
			"62": "William Turner",
			"63": "Edvard Munch",
			"64": "Antoine Watteau",
			"65": "William Adolphe Bouguereau",
			"66": "John Constable",
			"67": "John Everett Millais",
			"68": "Pieter de Hooch",
			"69": "Paul Cézanne",
			"70": "Théodore Géricault",
			"71": "Thomas Gainsborough",
			"72": "William Blake",
			"73": "Eugène Delacroix",
			"74": "Jan Vermeer",
			"75": "Henri Rousseau",
			"76": "Wladimir Borowikowski",
			"77": "Georges Seurat",
			"78": "Lucian Freud",
			"79": "Paul Klee",
			"80": "Piet Mondrian",
			"81": "Pawel Filonow",
			"82": "Joan Miró",
			"83": "Andy Warhol",
			"84": "Walentin Serow",
			"85": "Alexei Harlamov",
			"86": "Wassili Tropinin",
			"87": "Fra Angelico",
			"88": "Edward Burne-Jones",
			"89": "Martin Schongauer",
			"90": "Rogier van der Weyden",
			"91": "Giovanni di Paolo",
			"92": "Hans Baldung",
			"93": "Gustave Moreau",
			"94": "Paul Gauguin",
			"95": "Raffael",
			"96": "Paul Signac",
			"97": "Nicolas Poussin",
			"98": "Hans Holbein der Jüngere",
			"99": "William Holman Hunt",
			"100": "Albrecht Altdorfer",
			"101": "Antonello da Messina",
			"102": "Arthur Hughes",
			"103": "Alexander Benois",
			"104": "Hans Memling",
			"105": "Alexander Deineka",
			"106": "Giorgione",
			"107": "Alexander Iwanow",
			"108": "Antonio da Correggio",
			"109": "Dmitry Levitzky",
			"110": "Lucas van Leyden",
			"111": "Lucas Cranach der Ältere",
			"112": "Michelangelo",
			"113": "Nikolai Ge",
			"114": "Robert Campin",
			"115": "Fyodor Rokotov",
			"116": "Rockwell Kent",
			"117": "Martiros Sarjan",
			"118": "Jackson Pollock"
		},
		"nation": {
			"Russian": "Russisch",
			"Armenian": "Armenier",
			"Italian": "Italiener",
			"French": "Französisch",
			"Mexican": "Mexikaner",
			"Belgian": "Belgier",
			"Spanish": "Spanisch",
			"American": "Amerikaner",
			"Dutch": "Holländer",
			"Austrian": "Österreicher",
			"Flemish": "Flämischer",
			"German": "Deutsch",
			"British": "Britische",
			"Jewish": "Jude",
			"Belarusian": "Weißrusse",
			"Czech": "Tschechische",
			"Greek": "Griechisch",
			"Norwegian": "Norwegische",
			"Ukrainian": "Ukrainisch",
			"Swiss": "Schweizer"
		},
		"genre": {
			"Romanticism": "Romantik",
			"Expressionism": "Expressionismus",
			"Impressionism": "Impressionismus",
			"Realism": "Realismus",
			"Abstractionism": "Abstractionism",
			"Symbolism": "Symbolik",
			"Muralism": "Wandmalerei",
			"Social Realism": "Sozialen Realismus",
			"Surrealism": "Surrealismus",
			"Byzantine Art": "Byzantinische Kunst",
			"Post-Impressionism": "Post-Impressionismus",
			"Art Nouveau": "Art Nouveau",
			"Northern Renaissance": "Northern Renaissance",
			"Suprematism": "Suprematismus",
			"Cubism": "Kubismus",
			"Baroque": "Barock",
			"Iconography": "Ikonographie",
			"Primitivism": "Primitivismus",
			"Mannerism": "Manierismus",
			"Neoclassicism": "Neoklassizismus",
			"Proto Renaissance": "Proto Renaissance",
			"Early Renaissance": "Frührenaissance",
			"Art Deco": "Art Deco",
			"High Renaissance": "Hochrenaissance",
			"Aestheticism": "Ästhetizismus",
			"Analytical Realism": "Analytische Realismus",
			"Neoplasticism": "Neoplastizismus",
			"Rococo": "Rokoko",
			"Pop Art": "Pop Art",
			"Socialist Realism": "Sozialistischer Realismus",
			"Academic Art": "Akademische Kunst",
			"Abstract Expressionism": "Abstrakter Expressionismus"
		},
		"sets": {
			"basicSet": "Die bekannten Maler",
			"basicSet-desc": "Die Sammlung der Bilder von den bekannten Malern",
			"basicSet-count": "50 Malern, 8 450 Gemälde",
			"renaissanceSet": "Die Renaissance",
			"renaissanceSet-desc": "Von Nord-Renaissance und Protorenaissance bis Hochrenaissance",
			"renaissanceSet-count": "24 Malern, 2 783 Gemälde",
			"impressionismSet" : "Der Impressionismus und der Postimpressionismus",
			"impressionismSet-desc" : "Die Werke von den Malern von dem Impressionismus und dem Postimpressionismus",
			"impressionismSet-count": "18 Malern, 4 231 Gemälde",
			"realismSet": "Malern des Realismus",
			"realismSet-desc": "Die Sammlung von den Bildern von Malern des Realismus",
			"realismSet-count": "12 Malern, 2 083 Gemälde",
			"russianSet": "Die russischen Maler",
			"russianSet-desc": "Von allen Zeiten und verschiedenen Malerschulen",
			"russianSet-count": "33 Malern, 5 140 Gemälde",
			"frenchSet": "Die französischen Maler",
			"frenchSet-desc": "Die Sammlung von französischen Malern",
			"frenchSet-count": "22 Malern, 3 758 Gemälde",
			"allSet": "Die volle Sammlung",
			"allSet-desc": "Die Bilder von allen zum Spiel eingefuegten Maler – fuer beschlagene Spieler",
			"allSet-count": "118 Malern, 17 695 Gemälde"
		}
	}];
	var es = [{
		"head": {
			"title": "Art Challenge – El juego de preguntas sobre pintores famosos",
			"description": "¡Trata de adivinar 10 pintores del tirón y gana a tus amigos!"
		},
		"desc": {
			"what": "¿Qué esta pasando aquí?",
			"what-desc": "¡Te estamos ofreciendo algo de diversión jugando al juego de la historia del arte!",
			"how": "¿Cómo funciona?",
			"how-desc": "Tienes que adivinar los artistas que hicieron cuadros conocidos.<br>Ganarás si logras adivinar 10 pintores consecutivos.",
			"what-good": "¿Para qué sirve?",
			"what-good-desc": "Juega en tu tiempo libre y pronto serás capaz de distinguir con un vistazo a Claude Monet de Edouard Manet, por no hablar de Alfred Sisley :)",
			"how-help": "¿Cómo puedo ayudar?",
			"how-help-desc": "Si te gusta esta página ¿tendrías la amabilidad de compartirla con tus amigos?",
			"settings": "Opciones",
			"lang": "Idioma",
			"swear": "Blasfemias",
      "emoji": "Emoticones",
			"swear-on": "On",
			"swear-off": "Off",
			"subscribe": "Suscíbete para recibir noticias:",
			"press": "Pulse sobre nosotros:",
			"menu": "Menú",
			"menuSinglePlayer": "Un jugador",
			"menuDuel": "Duelo con un amigo",
			"menuTournament": "Mejores jugadores",
			"setCurrent": "Colección",
 			"setChooseDesc": "Elige una colección",
			"setChooseBtn": "Juega ahora",
			"setPlayingNow": "Estás jugando en esta colección ahora",
			"statsTitle": "Estadística",
			"statsAnswersByDays": "Mis respuestas por días",
			"statsNoDataText": "Has jugado muy poco en la colección <b>__setName__</b>, juégala durante un par de días y aquí aparecerá una gráfica de tus respuestas.",
			"statsCollectionKnow": "Mi conocimiento de colecciones",
			"statsLastAnswers": "Mis últimas respuestas",
			"statsPainting": "Cuadro",
			"statsYourAnswer": "Tu respuesta",
      "statsMyProfile": "Mi perfil",
      "statsYourBestPainters": "Pintores que reconoces más seguido",
      "statsYourWorstPainters": "Pintores que reconoces menos seguido",
			"loginTitle": "Inscripción",
			"loginUnregisteredPlayer": "Jugador desconocido",
			"loginClickToRegister": "Pulsa para inscribirte",
			"loginName": "Nombre",
			"loginNameExample": "Por ejemplo, Juan Pérez",
			"loginEmail": "E-mail",
			"loginEmailExample": "Por ejemplo, juanperez@gmail.com",
			"loginBtnRegister": "Inscribirte",
			"loginRegisterDesc": "Al inscribirte vas a poder participar en el torneo y guardar la estadística de tus juegos.",
			"loginLoginForRegistered" : "Ya estás inscrito?",
			"loginLoginForRegisteredHint": "Introduce el e-mail que utilizaste en la inscripción",
			"loginBtnLogin": "Entrar",
			"loginMessageSuccessRegister": "Te has inscrito correctamente!",
			"loginMessageSuccessLogin": "Has entrado correctamente!",
			"loginSuccessEmailText": "__username__, gracias por la inscipción en Art Challenge!<br>Ahora puedes participar en el torneo y guardar la estadística de tus juegos.<br>Si tienes alguna pregunta, escríbenos a info@artchallenge.ru.<br>Si quieres seguir las noticias en el mundo del arte, entra en nuestras redes sociales:<br>VKontakte: http://vk.com/art.challenge<br>Facebook: http://facebook.com/artchallenge.ru<br><br>Un saludo del equipo de Art Challenge<br>Ruben and Anna.",
			"loginMessageErrorEmail": "Introduce un e-mail válido",
			"loginMessageError": "Introduce tu nombre y un e-mail válido",
			"loginMessageErrorDuplicate": "Se ha producido un error: Este e-mail ya está utilizado",
			"loginMessageErrorForbiddenName": "Se ha producido un error: Un nombre inválido",
			"loginMessageErrorServer": "Se ha producido un error: El servidor no responde, intenta otra vez más tarde",
      "errorOffline": "No hay conección con internet",
      "swipeCollections": "ELIGE UNA COLECCIÓN",
      "swipePictures": "DESLIZA CUADROS",
      "yourPlace": "__place__ lugar",
      "highQualityPictures": "Alta definición",
      "highQualityPicturesDesc": "Imágenes de alta definición van a ser descargadas del internet",
      "picturesInRow": "de un tirón",
      "reportError": "¿Encontraste un error?",
      "reportEmail": "Comunícalo sin falta al report@artchallenge.ru",
      "subscribeNoSpam": "Nada de spam. Sólo noticias extraordinarias del mundo de arte.",
      "about": "Sobre el juego",
      "aboutSponsors": "Art Challenge fue creado por Rubén Babáev y Anna Plótkina gracias al apoyo de nuestros queridos mecenas:",
      "gameVersion": "Versión del juego",
      "exit": "Salir"
		},
		"message": {
			"right": "¡Has acertado!",
			"right-desc": "El cuadro número __count__ adivinado",
			"wrong": "¡Incorrecto!",
			"wrong-desc": "Es",
			"years": "Años",
			"nationality": "Nacionalidad",
			"genre": "Género",
			"learn-more": "Aprende más",
			"winner": "¡Enhorabuena!",
			"winner-desc": "Colección de <strong>__setName__</strong> pasó!",
			"winner-desc-old": "¡Se te da muy bien el arte!<br>10 de los 10 – está bastante mejor que el 82% de la gente que ha jugado a esto!",
			"share": "Puedes compartir tu victoria con tus amigos:",
      "winnerMobile": "Te da muy bien la colección.",
      "shareOrTournament": "Cuenta a tus amigos sobre la victoria y participa en el torneo por la serie más larga de respuestas correctas:",
      "shareWithFriends": "Comparte con amigos",
      "playTournament": "Torneo",
      "loading": "Cargando",
      "closeWinTitle": "Empezar un nuevo juego",
      "closeWinMessage": "¿Quieres cerrar esta ventana y empezar un nuevo juego?"
		},
		"badPhrases": {
			"1": "¡Estás loco!",
			"2": "Maldita sea.. ¿qué?",
			"3": "¡Debería darte vergüenza!",
			"4": "¿Te encuentras mal o qué?",
			"5": "¡Esto es ridículo!",
			"6": "¿Y esa tontería?",
			"7": "¡Más te vale mejorar!",
			"8": "¡No, no y NO!",
			"9": "¡Piénsatelo mejor!",
			"10": "Lo siento, es incorrecto.",
			"11": "¿Qué demonios?",
			"12": "¡Madre mía!"
		},
		"goodPhrases": {
			"1": "¡Has acertado!",
			"2": "¡Así es!",
			"3": "¡Bravo!",
			"4": "¡Excelente!",
			"5": "¡Perfecto!",
			"6": "¡Magnífico!",
			"7": "¡Bien!",
			"8": "¡Justamente!",
			"9": "¡Exactamente!",
			"10": "¡Estupendo!",
			"11": "¡Correctamente!",
			"12": "¡Efectivamente!",
			"13": "¡Maravilloso!",
			"14": "¡Guay!",
			"15": "¡Increíble!",
			"16": "¡Has estado brillante!",
			"17": "¡De maravilla!",
			"18": "¡Extraordinario!",
			"19": "¡Eso es!",
			"20": "¡No hay duda!"
		},
		"shares": {
			"title": "Damas y caballeros, ¡soy muy bueno en esto del arte!",
			"description": "¡Trata de adivinar 10 pintores del tirón y gana a tus amigos!",
			"caption": "Art Challenge – El juego de preguntas sobre pintores famosos"
		},
		"footer": {
			"created": "Creado por",
			"ruben": "Ruben",
			"ruben-full": "Ruben Babaev",
			"and": "y",
			"anna": "Anna",
			"anna-full": "Anna Plotkina",
			"year": "en 2014",
			"vk": "VKontakte",
			"other-projects": "Otros de nuestros proyectos"
		},
		"painters": {
			"1": "Amedeo Modigliani",
			"2": "Henri Lebasque",
			"3": "Arkhip Kuinji",
			"4": "Vasili Kandinski",
			"5": "Vasili Súrikov",
			"6": "Victor Borisov-Musatov",
			"7": "Diego Rivera",
			"8": "Iván Shishkin",
			"9": "Claude Monet",
			"10": "Konstantin Yuon",
			"11": "Nikolái Roerich",
			"12": "Orest Kiprenski",
			"13": "Kuzmá Petrov-Vodkin",
			"14": "René Magritte",
			"15": "Salvador Dalí",
			"16": "Sergei Vinogradov",
			"17": "Édouard Manet",
			"18": "Andrew Wyeth",
			"19": "Andréi Rubliov",
			"20": "Víktor Vasnetsov",
			"21": "Vincent van Gogh",
			"22": "Gustav Klimt",
			"23": "Iván Aivazovski",
			"24": "Hieronymus Bosch",
			"25": "Iliá Repin",
			"26": "Kazimir Malévich",
			"27": "Mijaíl Vrúbel",
			"28": "Pablo Picasso",
			"29": "Peter Paul Rubens",
			"30": "Pierre-Auguste Renoir",
			"31": "Teófanes el griego",
			"32": "Francisco de Goya",
			"33": "Frida Kahlo",
			"34": "El Greco",
			"35": "Alberto Durero",
			"36": "Alfred Sisley",
			"37": "Borís Kustódiev",
			"38": "Karl Briulov",
			"39": "Pieter Brueghel",
			"40": "Marc Chagall",
			"41": "Giotto di Bondone",
			"42": "Sandro Botticelli",
			"43": "Caravaggio",
			"44": "Zinaída Serebriakova",
			"45": "Leonardo da Vinci",
			"46": "Diego Velázquez",
			"47": "Vasili Vereshchaguin",
			"48": "Isaak Levitán",
			"49": "Henri Matisse",
			"50": "Jan van Eyck",
			"51": "John Waterhouse",
			"52": "Egon Schiele",
			"53": "Edgar Degas",
			"54": "Rembrandt",
			"55": "Tiziano",
			"56": "Alfons Mucha",
			"57": "Henri de Toulouse-Lautrec",
			"58": "Gustave Courbet",
			"59": "Dante Gabriel Rossetti",
			"60": "John Singer Sargent",
			"61": "Camille Pissarro",
			"62": "William Turner",
			"63": "Edvard Munch",
			"64": "Antoine Watteau",
			"65": "William-Adolphe Bouguereau",
			"66": "John Constable",
			"67": "John Everett Millais",
			"68": "Pieter de Hooch",
			"69": "Paul Cézanne",
			"70": "Théodore Géricault",
			"71": "Thomas Gainsborough",
			"72": "William Blake",
			"73": "Eugène Delacroix",
			"74": "Johannes Vermeer",
			"75": "Henri Rousseau",
			"76": "Vladímir Borovikovski",
			"77": "Georges Pierre Seurat",
			"78": "Lucian Freud",
			"79": "Paul Klee",
			"80": "Piet Mondrian",
			"81": "Pavel Filonov",
			"82": "Joan Miró",
			"83": "Andy Warhol",
			"84": "Valentín Serov",
			"85": "Alexei Harlamov",
			"86": "Vasily Tropinin",
			"87": "Fra Angelico",
			"88": "Edward Burne-Jones",
			"89": "Martin Schongauer",
			"90": "Rogier van der Weyden",
			"91": "Giovanni di Paolo",
			"92": "Hans Baldung",
			"93": "Gustave Moreau",
			"94": "Paul Gauguin",
			"95": "Rafael",
			"96": "Paul Signac",
			"97": "Nicolas Poussin",
			"98": "Hans Holbein el Joven",
			"99": "William Holman Hunt",
			"100": "Albrecht Altdorfer",
			"101": "Antonello da Messina",
			"102": "Arthur Hughes",
			"103": "Alexandre Benois",
			"104": "Hans Memling",
			"105": "Alexander Deineka",
			"106": "Giorgione",
			"107": "Aleksandr Ivánov",
			"108": "Correggio",
			"109": "Dmitri Levitski",
			"110": "Lucas van Leyden",
			"111": "Lucas Cranach el Viejo",
			"112": "Miguel Ángel",
			"113": "Nikolai Ge",
			"114": "Robert Campin",
			"115": "Fyodor Rokotov",
			"116": "Rockwell Kent",
			"117": "Martiros Sarian",
			"118": "Jackson Pollock"
		},
		"nation": {
			"Russian": "Ruso",
			"Armenian": "Armenio",
			"Italian": "Italiano",
			"French": "Francés",
			"Mexican": "Mexicano",
			"Belgian": "Belga",
			"Spanish": "Español",
			"American": "Americano",
			"Dutch": "Holandés",
			"Austrian": "Austriaco",
			"Flemish": "Flamenco",
			"German": "Alemán",
			"British": "Británico",
			"Jewish": "Judio",
			"Belarusian": "Bielorruso",
			"Czech": "Checo",
			"Greek": "Griego",
			"Norwegian": "Noruega",
			"Ukrainian": "Ucranio",
			"Swiss": "Suiza"
		},
		"genre": {
			"Romanticism": "Romanticismo",
			"Expressionism": "Expresionismo",
			"Impressionism": "Impresionismo",
			"Realism": "Realismo",
			"Abstractionism": "Abstraccionismo",
			"Symbolism": "Simbolismo",
			"Muralism": "Muralismo",
			"Social Realism": "Realismo Social",
			"Surrealism": "Surrealismo",
			"Byzantine Art": "Arte Bizantino",
			"Post-Impressionism": "Post-Impresionismo",
			"Art Nouveau": "Art Nouveau",
			"Northern Renaissance": "Renacimiento del norte",
			"Suprematism": "Suprematismo",
			"Cubism": "Cubismo",
			"Baroque": "Barroco",
			"Iconography": "Iconografía",
			"Primitivism": "Primitivismo",
			"Mannerism": "Manierismo",
			"Neoclassicism": "Neoclasicismo",
			"Proto Renaissance": "Proto Renacimiento",
			"Early Renaissance": "Renacimiento temprano",
			"Art Deco": "Art Deco",
			"High Renaissance": "Alto Renacimiento",
			"Aestheticism": "Esteticismo",
			"Analytical Realism": "Realismo Analítico",
			"Neoplasticism": "Neoplasticismo",
			"Rococo": "Rococó",
			"Pop Art": "Arte Pop",
			"Socialist Realism": "Realismo Socialista",
			"Academic Art": "Academicismo",
			"Abstract Expressionism": "Expresionismo Abstracto"
		},
		"sets": {
			"basicSet": "Pintores famosos",
			"basicSet-desc": "Colección de los cuadros de los pintores más famosos ",
			"basicSet-count": "50 pintores, 8 450 pinturas",
			"renaissanceSet": "Renacimiento",
			"renaissanceSet-desc": "Del Renacimiento Nórdico y el Protorrenacimiento a la obra de Alto Renacimiento",
			"renaissanceSet-count": "24 pintores, 2 783 pinturas",
			"impressionismSet" : "Impresionismo y postimpresionismo",
			"impressionismSet-desc" : "La pintura impresionista y postimpresionista",
			"impressionismSet-count": "18 pintores, 4 231 pinturas",
			"realismSet": "Pintores realistas",
			"realismSet-desc": "La pintura del Realismo",
			"realismSet-count": "12 pintores, 2 083 pinturas",
			"russianSet": "Pintores rusos",
			"russianSet-desc": "La pintura de distintos períodos y tipos diferentes",
			"russianSet-count": "33 pintores, 5 140 pinturas",
			"frenchSet": "Pintores franceses",
			"frenchSet-desc": "La colección de la pintura francesa",
			"frenchSet-count": "22 pintores, 3 758 pinturas",
			"allSet": "Colección completa",
			"allSet-desc": "Los cuadros de todos los pintores incluidos en el juego – para los jugadores más avancados",
			"allSet-count": "118 pintores, 17 695 pinturas"
		}
	}];
	var fr = [{
		"head": {
			"title": "Art Challenge - Un jeu sur la connaissance des artistes populaires",
			"description": "Essayez de deviner 10 artistes de suite et battre vos amis!"
		},
		"desc": {
			"what": "Qu'est-ce qui se passe ici?",
			"what-desc": "Vous êtes invités à vous distraire avec le jeu sur la connaissance de l'histoire de l'art.",
			"how": "Comment ça marche?",
			"how-desc": "Vous devez deviner les auteurs de tableaux.<br>Ces messieurs qui peuvent deviner 10 tableaux de suite, gagnent.",
			"what-good": "A quoi ça sert?",
			"what-good-desc": "Jouez pendant votre temps libre, et bientôt vous pourrez distinguer facilement Claude Monet d' Edouard Manet et certainement d' Alfred Sisley d' un coup d'oeil :)",
			"how-help": "Comment puis-je vous aider? ",
			"how-help-desc": "Si ce site vous a plu, soyez gentil d' y raconter à vos amis",
			"settings": "Paramètres",
			"lang": "Langue",
			"swear": "Injures",
      "emoji": "Émoticônes",
			"swear-on": "Insérer",
			"swear-off": "Couper",
			"subscribe": "Abonnez-vous aux nouvelles:",
			"press": "Presse parle de nous:",
			"menu": "Menu",
			"menuSinglePlayer": "Pour un joueur",
			"menuDuel": "Duel avec un ami",
			"menuTournament": "Meilleurs Joueurs",
			"setCurrent": "Une collection actuelle",
 			"setChooseDesc": "Choisissez une collection",
			"setChooseBtn": "Jouer",
			"setPlayingNow": "Vous jouez à cette collection ",
			"statsTitle": "Statistique",
			"statsAnswersByDays": "Mes réponses par jours",
			"statsNoDataText": "Vous avez joué trop peu à cette collection <b>__setName__</b>, jouez y deux jours au minimum et vous verrez ici le graphique de vos réponses.",
			"statsCollectionKnow": "Mes connaissances de collections",
			"statsLastAnswers": "Mes dernières réponses",
			"statsPainting": "Tableau",
			"statsYourAnswer": "Votre réponse",
      "statsMyProfile": "Mon profil",
      "statsYourBestPainters": "Les peintres les plus reconnus",
      "statsYourWorstPainters": "Les peintres les moins reconnus",
			"loginTitle": "Enregistrement",
			"loginUnregisteredPlayer": "Un joueur inconnu",
			"loginClickToRegister": "Claquer pour être enregistré",
			"loginName": "Nom",
			"loginNameExample": "Par exemple, Charles Aznavourian",
			"loginEmail": "E-mail",
			"loginEmailExample": "Par exemple, charlesaznavourian@gmail.com",
			"loginBtnRegister": "Enregistrer",
			"loginRegisterDesc": "L'enregistrement vous permettra de participer au tournoi et de garder la statistique de vos jeux.",
			"loginLoginForRegistered" : "Etes-vous déjà enregistré?",
			"loginLoginForRegisteredHint": "Introduisez e-mail utilisé pendant l'enregistrement. ",
			"loginBtnLogin": "Se connecter",
			"loginMessageSuccessRegister": "Vous êtes successivement enregistré!",
			"loginMessageSuccessLogin": "Vous vous êtes successivement connecté!",
			"loginSuccessEmailText": "__username__, merci pour votre enregistrement en Art Challenge!<br> Maintenant vous pouvez participer au tournoi et étudier la statistique de vos jeux. Si vous avez des questions, connectez-nous sur info@artchallenge.ru.<br> Si vous voulez être au courant des actuaités du monde de l'art, suivez-nous aux réseaux sociaux:<br>VKontakte: http://vk.com/art.challenge<br>Facebook: http://facebook.com/artchallenge.ru<br><br>Sincèrement, l'equipe d'Art Challenge<br>Ruben et Anna.",
			"loginMessageErrorEmail": "Introduisez un E-mail valide",
			"loginMessageError": "Introduisez votre nom d'utilisateur et votre E-mail valide",
			"loginMessageErrorDuplicate": "Faute d'enregistrement: il y a déjà un utilisateur  avec la même adresse électronique",
			"loginMessageErrorForbiddenName": "Faute d'enregistrement: le nom d'utilisateur intérdit.",
			"loginMessageErrorServer": "Faute d'enregistrement: Le server est inaccessible, essayez encore une fois plus tard ",
      "errorOffline": "Pas de connection de l'internet",
      "swipeCollections": "CHOISISSEZ UNE COLLECTION",
      "swipePictures": "Feuilletez des tableaux",
      "yourPlace": "Vous êtes au__place__ place",
      "highQualityPictures": "Une haute qualité",
      "highQualityPicturesDesc": "Les tableaux de haute qualité seront chargés de l`internet",
      "picturesInRow": "de suite",
      "reportError": "Avez-vous trouvez une faute?",
      "reportEmail": "Faites-nous savoir tout de suite à report@artchallenge.ru",
      "subscribeNoSpam": "Pas de spam. Seulement remarquables actualités du monde de l`art.",
      "about": "A propos du jeu",
      "aboutSponsors": "Art Challenge est crée par Ruben Babaev et Anna Plotkina grâce à l'appui de nos chers mécènes:",
      "gameVersion": "Une vérsion du jeu",
      "exit": "Se déconnecter"
		},
		"message": {
			"right": "Exact!",
			"right-desc": "Vous avez deviné __count__ le tableau",
			"wrong": "Faux!",
			"wrong-desc": "C'est",
			"years": "Années de vie",
			"nationality": "Nationalité",
			"genre": "Genres",
			"learn-more": "Savoir plus",
			"winner": "Félicitations!",
			"winner-desc": "Collection <strong>__setName__</strong> passé!",
			"winner-desc-old": "Vous êtes un connaisseur de l'art!<br>10 sur 10 - c' est mieux que 82% des gens qui ont joué ce jeu!",
			"share": "Vous pouvez parler de votre victoire dans les réseaux sociaux:",
      "winnerMobile": "Vous êtes forts en cette collection!",
      "shareOrTournament": "Racontez vos amis de votre victoire et prenez part en tournoi sur la plus longue série de réponses correctes:",
      "shareWithFriends": "En parler à vos amis",
      "playTournament": "Tournoi",
      "loading": "Chargement",
      "closeWinTitle": "Commencer un nouveau jeu",
      "closeWinMessage": "Voulez-vous fermer la fenêtre et commencer un nouveau jeu?"
		},
		"badPhrases": {
			"1": "Mais, vous êtes fou!",
			"2": "N' avez-vous pas d' honte?",
			"3": "Êtes-vous malades?",
			"4": "Quelle absurdité!",
			"5": "Faites d' autodidaxie!",
			"6": "Comment pourriez-vous?",
			"7": "Non, non et non!",
			"8": "Ravisez-vous!",
			"9": "Et si vous pensez?",
			"10": "Zut!",
			"11": "Incivilités!",
			"12": "Collègue!"
		},
		"goodPhrases": {
			"1": "Bien!",
			"2": "Juste!",
			"3": "Bravo!",
			"4": "Parfaitement!",
			"5": "Superbe!",
			"6": "Admirablement!",
			"7": "Bien fait!",
			"8": "Tout à fait juste!",
			"9": "C'est parfaitement exact!",
			"10": "Exactement!",
			"11": "C`est vrai!",
			"12": "Incontestablement!",
			"13": "Sans blagues, c`est vrai!",
			"14": "C`est manifique!",
			"15": "Excellent!",
			"16": "Brillamment!",
			"17": "Admirablement!",
			"18": "C'est super!",
			"19": "C'est énorme!",
			"20": "Chic, alors!!!!"
		},
		"shares": {
			"title": "Messieurs, c' est moi qui comprends en art!",
			"description": "Essayez de deviner 10 artistes de suite et battre vos amis!",
			"caption": "Art Challenge - Un jeu sur la connaissance des artistes populaires"
		},
		"footer": {
			"created": "Site est créé par",
			"ruben": "Ruben",
			"ruben-full": "Ruben Babaev",
			"and": "et",
			"anna": "Anna",
			"anna-full": "Anna Plotkina",
			"year": "en 2014",
			"vk": "VKontakte",
			"other-projects": "Nos projets"
		},
		"painters": {
			"1": "Amedeo Modigliani",
			"2": "Henri Lebasque",
			"3": "Arkhip Kouïndji",
			"4": "Vassily Kandinsky",
			"5": "Vassili Sourikov",
			"6": "Victor Borissov-Moussatov",
			"7": "Diego Rivera",
			"8": "Ivan Chichkine",
			"9": "Claude Monet",
			"10": "Constantin Youon",
			"11": "Nicolas Roerich",
			"12": "Oreste Kiprensky",
			"13": "Kouzma Petrov-Vodkine",
			"14": "René Magritte",
			"15": "Salvador Dalí",
			"16": "Sergueï Vinogradov",
			"17": "Édouard Manet",
			"18": "Andrew Wyeth",
			"19": "Andreï Roublev",
			"20": "Victor Vasnetsov",
			"21": "Vincent van Gogh",
			"22": "Gustav Klimt",
			"23": "Ivan Aïvazovski",
			"24": "Jérôme Bosch",
			"25": "Ilya Repine",
			"26": "Kasimir Malevitch",
			"27": "Mikhaïl Vroubel",
			"28": "Pablo Picasso",
			"29": "Pierre Paul Rubens",
			"30": "Pierre-Auguste Renoir",
			"31": "Théophane le Grec",
			"32": "Francisco de Goya",
			"33": "Frida Kahlo",
			"34": "El Greco",
			"35": "Albrecht Dürer",
			"36": "Alfred Sisley",
			"37": "Boris Koustodiev",
			"38": "Karl Brioullov",
			"39": "Pieter Brueghel",
			"40": "Marc Chagall",
			"41": "Giotto di Bondone",
			"42": "Sandro Botticelli",
			"43": "Le Caravage",
			"44": "Zinaïda Serebriakova",
			"45": "Léonard de Vinci",
			"46": "Diego Vélasquez",
			"47": "Vassili Verechtchaguine",
			"48": "Isaac Levitan",
			"49": "Henri Matisse",
			"50": "Jan van Eyck",
			"51": "John Waterhouse",
			"52": "Egon Schiele",
			"53": "Edgar Degas",
			"54": "Rembrandt",
			"55": "Titien",
			"56": "Alfons Mucha",
			"57": "Henri de Toulouse-Lautrec",
			"58": "Gustave Courbet",
			"59": "Dante Gabriel Rossetti",
			"60": "John Singer Sargent",
			"61": "Camille Pissarro",
			"62": "William Turner",
			"63": "Edvard Munch",
			"64": "Antoine Watteau",
			"65": "William-Adolphe Bouguereau",
			"66": "John Constable",
			"67": "John Everett Millais",
			"68": "Pieter de Hooch",
			"69": "Paul Cézanne",
			"70": "Théodore Géricault",
			"71": "Thomas Gainsborough",
			"72": "William Blake",
			"73": "Eugène Delacroix",
			"74": "Johannes Vermeer",
			"75": "Henri Rousseau",
			"76": "Vladimir Borovikovski",
			"77": "Georges Seurat",
			"78": "Lucian Freud",
			"79": "Paul Klee",
			"80": "Piet Mondrian",
			"81": "Pavel Filonov",
			"82": "Joan Miró",
			"83": "Andy Warhol",
			"84": "Valentin Serov",
			"85": "Alexei Harlamov",
			"86": "Vassili Tropinine",
			"87": "Fra Angelico",
			"88": "Edward Burne-Jones",
			"89": "Martin Schongauer",
			"90": "Rogier van der Weyden",
			"91": "Giovanni di Paolo",
			"92": "Hans Baldung",
			"93": "Gustave Moreau",
			"94": "Paul Gauguin",
			"95": "Raphaël",
			"96": "Paul Signac",
			"97": "Nicolas Poussin",
			"98": "Hans Holbein",
			"99": "William Holman Hunt",
			"100": "Albrecht Altdorfer",
			"101": "Antonello de Messine",
			"102": "Arthur Hughes",
			"103": "Alexandre Benois",
			"104": "Hans Memling",
			"105": "Aleksandr Deyneka",
			"106": "Giorgione",
			"107": "Alexandre Ivanov",
			"108": "Correggio",
			"109": "Dmitry Levitzky",
			"110": "Lucas van Leyden",
			"111": "Lucas Cranach l'Ancien",
			"112": "Michel-Ange",
			"113": "Nikolai Ge",
			"114": "Robert Campin",
			"115": "Fedor Rokotov",
			"116": "Rockwell Kent",
			"117": "Martiros Sarian",
			"118": "Jackson Pollock"
		},
		"nation": {
			"Russian": "Russe",
			"Armenian": "Arménien",
			"Italian": "Italien",
			"French": "Français",
			"Mexican": "Mexicain",
			"Belgian": "Belge",
			"Spanish": "Espagnol",
			"American": "Américain",
			"Dutch": "Néerlandais",
			"Austrian": "Autrichien",
			"Flemish": "Flamand",
			"German": "Allemand",
			"British": "Britannique",
			"Jewish": "Juif",
			"Belarusian": "Biélorusse",
			"Czech": "Tchèque",
			"Greek": "Grecque",
			"Norwegian": "Norvégienne",
			"Ukrainian": "Ukrainien",
			"Swiss": "Suisse"
		},
		"genre": {
			"Romanticism": "Romantisme",
			"Expressionism": "Expressionnisme",
			"Impressionism": "Impressionnisme",
			"Realism": "Réalisme",
			"Abstractionism": "L'Abstraction",
			"Symbolism": "Symbolisme",
			"Muralism": "Muralisme",
			"Social Realism": "Réalisme Social",
			"Surrealism": "Surréalisme",
			"Byzantine Art": "Art Byzantin",
			"Post-Impressionism": "Post-Impressionnisme",
			"Art Nouveau": "Art Nouveau",
			"Northern Renaissance": "Renaissance du Nord",
			"Suprematism": "Suprématisme",
			"Cubism": "Cubisme",
			"Baroque": "Baroque",
			"Iconography": "Iconographie",
			"Primitivism": "Primitivisme",
			"Mannerism": "Maniérisme",
			"Neoclassicism": "Néoclassicisme",
			"Proto Renaissance": "Proto Renaissance",
			"Early Renaissance": "Début de la Renaissance",
			"Art Deco": "Art Déco",
			"High Renaissance": "Haute Renaissance",
			"Aestheticism": "Esthétisme",
			"Analytical Realism": "Réalisme Analytique",
			"Neoplasticism": "Néoplasticisme",
			"Rococo": "Rococo",
			"Pop Art": "Pop Art",
			"Socialist Realism": "Réalisme socialiste soviétique",
			"Academic Art": "Art Académique",
			"Abstract Expressionism": "Expressionnisme Abstrait"
		},
		"sets": {
			"basicSet": "Des Artistes populaires",
			"basicSet-desc": "La collection des tableaux des artistes les plus connus",
			"basicSet-count": "50 peintres, 8 450 peintures",
			"renaissanceSet": "La Renaissance",
			"renaissanceSet-desc": "Depuis la Renaissance du nord et Protorenaissance vers les tableaux de la grande Renaissance",
			"renaissanceSet-count": "24 peintres, 2 783 peintures",
			"impressionismSet" : "L'Impressionisme et le Postimpressionisme",
			"impressionismSet-desc" : "Les oeuvres des impressionistes et des postimpressionistes",
			"impressionismSet-count": "18 peintres, 4 231 peintures",
			"realismSet": "Les Réalistes",
			"realismSet-desc": "La collection de tableaux des Réalistes",
			"realismSet-count": "12 peintres, 2 083 peintures",
			"russianSet": "Des artistes russes",
			"russianSet-desc": "Des artistes russes des toutes les époques et de styles differents",
			"russianSet-count": "33 peintres, 5 140 peintures",
			"frenchSet": "Des artistes français",
			"frenchSet-desc": "La collection de tableaux des artistes francais",
			"frenchSet-count": "22 peintres, 3 758 peintures",
			"allSet": "Collection complète",
			"allSet-desc": "Les tableaux de tous les artistes présentés en jeu - pour les joueurs qui ont plus d'expérience",
			"allSet-count": "118 peintres, 17 695 peintures"
		}
	}];
	var it = [{
		"head": {
			"title": "Art Challenge – è un gioco sulla conoscenza degli artisti più popolari",
			"description": "Provi a indovinare 10 artisti di seguito e superi i Suoi amici!"
		},
		"desc": {
			"what": "Che cosa sta succedendo qua?",
			"what-desc": "Le proponiamo di divertirsi con un gioco sulla conoscenza della storia dell’arte.",
			"how": "Come funziona?",
			"how-desc": "Bisogna indovinare gli autori delle opere.<br>Vincono coloro i quali riescono a indovinare 10 opere consecutivamente.",
			"what-good": "Che cosa me ne viene?",
			"what-good-desc": "Giochi a tempo libero e molto presto potrà distinguere senza fatica il Monet dal Manet a prima vista, e poi sicuramente dal Sisley :)",
			"how-help": "Come posso dare una mano?",
			"how-help-desc": "Se Le è piaciuto il sito, sia così cortese da raccontarlo ai Suoi amici",
			"settings": "Impostazioni",
			"lang": "Lingua",
			"swear": "Parolacce",
      "emoji": "Emoticon",
			"swear-on": "Acceso",
			"swear-off": "Spento",
			"subscribe": "Si iscriva alle notizie:",
			"press": "Premere su di noi:",
			"menu": "Menu",
			"menuSinglePlayer": "Giocatore singolo",
			"menuDuel": "Duella con un amico",
			"menuTournament": "Miglior giocatore",
			"setCurrent": "Collezione",
 			"setChooseDesc": "Scelga una collezione",
			"setChooseBtn": "Giochi ora",
			"setPlayingNow": "Non sta giocando in questa collezione",
			"statsTitle": "Statistica",
			"statsAnswersByDays": "I miei progressi giorno per giorno",
			"statsNoDataText": "Troppe poche partite nella collezione di <b>__setName__</b>, giochi per qualche giorno e le mostreremo un grafico con le sue risposte.",
			"statsCollectionKnow": "La mia conoscenza delle collezioni",
			"statsLastAnswers": "Le mie ultime risposte",
			"statsPainting": "Dipinto",
			"statsYourAnswer": "La sua risposta",
      "statsMyProfile": "Il mio profilo",
      "statsYourBestPainters": "Artisti più riconosciuti",
      "statsYourWorstPainters": "Artisti meno riconosciuti",
			"loginTitle": "Registrati",
			"loginUnregisteredPlayer": "Giocatore sconosciuto",
			"loginClickToRegister": "Clicca per registrarti",
			"loginName": "Nome",
			"loginNameExample": "Per esempio, Mario Rossi",
			"loginEmail": "E-mail",
			"loginEmailExample": "Per esempio, mariorossi@gmail.com",
			"loginBtnRegister": "Registrati",
			"loginRegisterDesc": "La registrazione le permetterà di partecipare ai tornei e tenere le statistiche delle sue partite",
			"loginLoginForRegistered" : "Già registrato?",
			"loginLoginForRegisteredHint": "E-mail usata per la registrazione",
			"loginBtnLogin": "Login",
			"loginMessageSuccessRegister": "Si è registrato correttamente",
			"loginMessageSuccessLogin": "E' entrato correttamente",
			"loginSuccessEmailText": "__username__,grazie per essersi registrato a Art Challenge!<br>Ora può partecipare ai tornei e monitorare le statistiche delle sue partite.<br>Per qualsiasi informazione o domanda ci contatti a info@artchallenge.ru.<br>Se vuole seguire le notizie dal mondo della culturaseguici sui social networks:<br>VKontakte: http://vk.com/art.challenge<br>Facebook: http://facebook.com/artchallenge.ru<br><br>Sincerely, Art Challenge Team<br>Ruben and Anna.",
			"loginMessageErrorEmail": "Introduca una e-mail valida",
			"loginMessageError": "Introduca il suo user name e una E-mail valida",
			"loginMessageErrorDuplicate": "Errore di registrazione:User con questa e-mail esistono già",
			"loginMessageErrorForbiddenName": "Errore diregistrazione:Username dimenticato",
			"loginMessageErrorServer": "Errore di registrazione:Il server non è disponibile,prova più tardi",
      "errorOffline": "Nessuna connessione internet",
      "swipeCollections": "SCELGA UNA COLLEZIONE",
      "swipePictures": "SFOGLIA I DIPINTI",
      "yourPlace": "__luogo__ luogo",
      "highQualityPictures": "Alta definizione",
      "highQualityPicturesDesc": "Immagini in alta definizione verranno scaricate da internet in fila",
      "picturesInRow": "in a row",
      "reportError": "Ha trovato qualche errore?",
      "reportEmail": "Ce lo comunichi a: report@artchallenge.ru",
      "subscribeNoSpam": "Niente spam. Solo notizie meravigliose sul mondo dell'arte.",
      "about": "Su questo gioco",
      "aboutSponsors": "Art Challenge è stato creato da: Ruben Babaiev e Anna Plotkina grazie al sostegno dei nostri cari mecenati:",
      "gameVersion": "Versione",
      "exit": "Uscita"
		},
		"message": {
			"right": "Giusto!",
			"right-desc": "Lei ha indovinato __count__ opera",
			"right-desc_plural": "Lei ha indovinato __count__ opere",
			"wrong": "Sbagliato!",
			"wrong-desc": "Ma è",
			"years": "Anni di vita",
			"nationality": "Nazionalità",
			"genre": "Pittura di genere",
			"learn-more": "Saperne di più",
			"winner": "Augurissimi!",
			"winner-desc": "La collezione <strong>__setName__</strong> è superata!",
			"winner-desc-old": "Lei è perfettamente versato/a nell'arte!<br>10 su 10 – è meglio del 82% delle persone che hanno partecipato a questo gioco!",
			"share": "Può condividere la Sua vittoria nelle reti sociali:",
      "winnerMobile": "Sei veramente bravo sulla collezione",
      "shareOrTournament": "Racconta ai tuoi amici della vittoria e partecipa ai tornei per la più lunga serie di risposte corrette",
      "shareWithFriends": "Condividilo con gli amici",
      "playTournament": "Torneo",
      "loading": "Caricamento",
      "closeWinTitle": "Inizia una nuova partita",
      "closeWinMessage": "Vuoi chiudere questa finestra e iniziare una nuova partita"
		},
		"badPhrases": {
			"1": "Ma Lei è impazito/a?",
			"2": "Non si vergogna?",
			"3": "Non si sente bene?",
			"4": "Сhe assurdità!",
			"5": "Si istruisca meglio!",
			"6": "Ma come Lei ha potuto!",
			"7": "No, no e no!",
			"8": "Ma ci ripensi!",
			"9": "Ma ripensandoci?",
			"10": "Che diavolo?!",
			"11": "Che crassa ignoranza!",
			"12": "Collega!"
		},
		"goodPhrases": {
			"1": "Giusto!",
			"2": "Esatto!",
			"3": "Perfetto!",
			"4": "Corretto!",
			"5": "Ottimo!",
			"6": "Incredibile!",
			"7": "Senza dubbio!",
			"8": "Che classe!",
			"9": "Meraviglioso!",
			"10": "Bravo/a!",
			"11": "Bravissimo/a!",
			"12": "Che maestria!",
			"13": "Fantastico!",
			"14": "Favoloso!",
			"15": "Stupendo!",
			"16": "Impressionante!",
			"17": "Ammirabile!",
			"18": "Magnifico!",
			"19": "Splendido!",
			"20": "Appropriato!"
		},
		"shares": {
			"title": "Signori, io sono un esperto dell’arte!",
			"description": "Art Challenge – è un gioco sulla conoscenza degli artisti più popolari",
			"caption": "Provi a indovinare 10 artisti di seguito e superi i Suoi amici!"
		},
		"footer": {
			"created": "Il sito è stato creato",
			"ruben": "da Ruben Babaiev",
			"ruben-full": "Ruben Babaev",
			"and": "e",
			"anna": "Anna Plotkina",
			"anna-full": "Anna Plotkina",
			"year": "nell’anno 2014",
			"vk": "VKontakte",
			"other-projects": "Altri nostri progetti"
		},
		"painters": {
			"1": "Amedeo Modigliani",
			"2": "Henri Lebasque",
			"3": "Archip Kuindži",
			"4": "Vasilij Kandinskij",
			"5": "Vasilij Surikov",
			"6": "Viktor Borisov-Musatov",
			"7": "Diego Rivera",
			"8": "Ivan Šiškin",
			"9": "Claude Monet",
			"10": "Konstantin Yuon",
			"11": "Nikolaj Roerich",
			"12": "Orest Kiprenskij",
			"13": "Kuzma Petrov-Vodkin",
			"14": "René Magritte",
			"15": "Salvador Dalí",
			"16": "Sergei Vinogradov",
			"17": "Édouard Manet",
			"18": "Andrew Wyeth",
			"19": "Andrej Rublëv",
			"20": "Viktor Vasnecov",
			"21": "Vincent van Gogh",
			"22": "Gustav Klimt",
			"23": "Ivan Ajvazovskij",
			"24": "Hieronymus Bosch",
			"25": "Il'ja Repin",
			"26": "Kazimir Malevič",
			"27": "Michail Vrubel'",
			"28": "Pablo Picasso",
			"29": "Pieter Paul Rubens",
			"30": "Pierre-Auguste Renoir",
			"31": "Teofane il Greco",
			"32": "Francisco Goya",
			"33": "Frida Kahlo",
			"34": "El Greco",
			"35": "Albrecht Dürer",
			"36": "Alfred Sisley",
			"37": "Boris Kustodiev",
			"38": "Karl Brjullov",
			"39": "Pieter Bruegel",
			"40": "Marc Chagall",
			"41": "Giotto di Bondone",
			"42": "Sandro Botticelli",
			"43": "Caravaggio",
			"44": "Zinaida Serebriakova",
			"45": "Leonardo da Vinci",
			"46": "Diego Velázquez",
			"47": "Vasilij Vereščagin",
			"48": "Isaak Levitan",
			"49": "Henri Matisse",
			"50": "Jan van Eyck",
			"51": "John Waterhouse",
			"52": "Egon Schiele",
			"53": "Edgar Degas",
			"54": "Rembrandt",
			"55": "Tiziano",
			"56": "Alfons Mucha",
			"57": "Henri de Toulouse-Lautrec",
			"58": "Gustave Courbet",
			"59": "Dante Gabriel Rossetti",
			"60": "John Singer Sargent",
			"61": "Camille Pissarro",
			"62": "William Turner",
			"63": "Edvard Munch",
			"64": "Antoine Watteau",
			"65": "William-Adolphe Bouguereau",
			"66": "John Constable",
			"67": "John Everett Millais",
			"68": "Pieter de Hooch",
			"69": "Paul Cézanne",
			"70": "Théodore Géricault",
			"71": "Thomas Gainsborough",
			"72": "William Blake",
			"73": "Eugène Delacroix",
			"74": "Jan Vermeer",
			"75": "Henri Rousseau",
			"76": "Vladimir Borovikovsky",
			"77": "Georges Seurat",
			"78": "Lucian Freud",
			"79": "Paul Klee",
			"80": "Piet Mondrian",
			"81": "Pavel Filonov",
			"82": "Joan Miró",
			"83": "Andy Warhol",
			"84": "Valentin Serov",
			"85": "Alexei Harlamov",
			"86": "Vasilij Tropinin",
			"87": "Beato Angelico",
			"88": "Edward Burne-Jones",
			"89": "Martin Schongauer",
			"90": "Rogier van der Weyden",
			"91": "Giovanni di Paolo",
			"92": "Hans Baldung",
			"93": "Gustave Moreau",
			"94": "Paul Gauguin",
			"95": "Raffaello Sanzio",
			"96": "Paul Signac",
			"97": "Nicolas Poussin",
			"98": "Hans Holbein il Giovane",
			"99": "William Holman Hunt",
			"100": "Albrecht Altdorfer",
			"101": "Antonello da Messina",
			"102": "Arthur Hughes",
			"103": "Aleksandr Benois",
			"104": "Hans Memling",
			"105": "Aleksandr Deyneka",
			"106": "Giorgione",
			"107": "Aleksandr Ivanov",
			"108": "Correggio",
			"109": "Dmitry Levitzky",
			"110": "Luca da Leida",
			"111": "Lucas Cranach il Vecchio",
			"112": "Michelangelo Buonarroti",
			"113": "Nikolaj Ge",
			"114": "Robert Campin",
			"115": "Fyodor Rokotov",
			"116": "Rockwell Kent",
			"117": "Martiros Saryan",
			"118": "Jackson Pollock"
		},
		"nation": {
			"Russian": "Russo",
			"Armenian": "Armeno",
			"Italian": "Italiano",
			"French": "Francese",
			"Mexican": "Messicano",
			"Belgian": "Belga",
			"Spanish": "Spagnolo",
			"American": "Americano",
			"Dutch": "Olandese",
			"Austrian": "Austriaco",
			"Flemish": "Fiammingo",
			"German": "Tedesco",
			"British": "Inglese",
			"Jewish": "Ebreo",
			"Belarusian": "Bielorusso",
			"Czech": "Ceco",
			"Greek": "Greco",
			"Norwegian": "Norvegese",
			"Ukrainian": "Ucraino",
			"Swiss": "Svizzero"
		},
		"genre": {
			"Romanticism": "Romanticismo",
			"Expressionism": "Espressionismo",
			"Impressionism": "Impressionismo",
			"Realism": "Realismo",
			"Abstractionism": "Astrattismo",
			"Symbolism": "Simbolismo",
			"Muralism": "Muralismo",
			"Social Realism": "Realismo Sociale",
			"Surrealism": "Surrealismo",
			"Byzantine Art": "Arte Bizantina",
			"Post-Impressionism": "Post-Impressionismo",
			"Art Nouveau": "Art Nouveau",
			"Northern Renaissance": "Rinascimento del Nord",
			"Suprematism": "Suprematismo",
			"Cubism": "Cubismo",
			"Baroque": "Barocco",
			"Iconography": "Iconografia",
			"Primitivism": "Primitivismo",
			"Mannerism": "Manierismo",
			"Neoclassicism": "Neoclassicismo",
			"Proto Renaissance": "Proto Rinascimento",
			"Early Renaissance": "Primo Rinascimento",
			"Art Deco": "Art Deco",
			"High Renaissance": "Alto Rinascimento",
			"Aestheticism": "Estetismo",
			"Analytical Realism": "Realismo Analitico",
			"Neoplasticism": "Neoplasticismo",
			"Rococo": "Rococò",
			"Pop Art": "Pop Art",
			"Socialist Realism": "Realismo Socialista",
			"Academic Art": "Art Pompier",
			"Abstract Expressionism": "Espressionismo Astratto"
		},
		"sets": {
			"basicSet": "Artisti più popolari",
			"basicSet-desc": "La collezione è composta dalle opere degli artisti più famosi",
			"basicSet-count": "50 pittori, 8 450 dipinti",
			"renaissanceSet": "Il rinascimento",
			"renaissanceSet-desc": "Dal Rinascimento nordico e pre-rinascimento al Pieno Rinascimento",
			"renaissanceSet-count": "24 pittori, 2 783 dipinti",
			"impressionismSet" : "Impressionismo e Post-impressionismo",
			"impressionismSet-desc" : "Le opere degli impressionisti e post-impressionisti",
			"impressionismSet-count": "18 pittori, 4 231 dipinti",
			"realismSet": "I pittori realisti",
			"realismSet-desc": "La collezione delle opere dei pittori realisti",
			"realismSet-count": "12 pittori, 2 083 dipinti",
			"russianSet": "Gli artisti russi",
			"russianSet-desc": "Di tutti i tempi e di diverse correnti ",
			"russianSet-count": "33 pittori, 5 140 dipinti",
			"frenchSet": "Gli artisti francesi",
			"frenchSet-desc": "La collezione delle opere degli artisti francesi",
			"frenchSet-count": "22 pittori, 3 758 dipinti",
			"allSet": "La collezione completa",
			"allSet-desc": "I dipinti di tutti gli artisti per giocatori più esperti",
			"allSet-count": "118 pittori, 17 695 dipinti"
		}
	}];

  var zh = [{
		"head": {
			"title": "艺术挑战－著名艺术家的问答题。",
			"description": "尝试猜对十位艺术家，挑战你的好友。"
		},
		"desc": {
			"what": "发生了什么？",
			"what-desc": "我们邀请你进行艺术历史的游戏。",
			"how": "这是如何创作的？",
			"how-desc": "你需要猜这幅画的作家是谁。<br> 如果猜对十个，你将会赢。",
			"what-good": "如何使用？",
			"what-good-desc": "在你的空闲时间游戏，那你很快就毫不费力地一眼就区分克洛德·莫奈<br>爱德华·马奈，当然还有阿尔弗雷德·西斯莱：）",
			"how-help": "喜欢艺术挑战吗？",
			"how-help-desc": "如果你喜欢我们的网站，分享他，并告诉你的朋友。",
			"settings": "设置",
			"lang": "语言",
			"swear": "笑话",
      "emoji": "emoji",
			"swear-on": "开",
			"swear-off": "关",
			"subscribe": "订阅消息",
			"press": "关于我们",
			"menu": "菜单",
			"menuSinglePlayer": "单人游戏",
			"menuDuel": "和朋友一起",
			"menuTournament": "最佳挑战者",
			"setCurrent": "收藏",
 			"setChooseDesc": "选择收藏",
			"setChooseBtn": "游戏开始",
			"setPlayingNow": "你玩这个收藏",
			"statsTitle": "统计",
			"statsAnswersByDays": "我每天的进步",
			"statsNoDataText": "你在这些收藏里玩的时间太少了，请至少玩两天，才能出现你的答案表格。",
			"statsCollectionKnow": "我的知识积累",
			"statsLastAnswers": "我最后一个回答",
			"statsPainting": "绘画",
			"statsYourAnswer": "你的答案",
      "statsMyProfile": "我的账户",
      "statsYourBestPainters": "最知名的艺术家",
      "statsYourWorstPainters": "不知名的艺术家",
			"loginTitle": "注册",
			"loginUnregisteredPlayer": "未注册玩家",
			"loginClickToRegister": "点击，进入",
			"loginName": "名字",
			"loginNameExample": "例如，张三",
			"loginEmail": "E-mail",
			"loginEmailExample": "例如，zhangsan@qq.com",
			"loginBtnRegister": "登陆",
			"loginRegisterDesc": "注册允许你参加比赛，并保存你的游戏记录。",
			"loginLoginForRegistered" : "已经注册？",
			"loginLoginForRegisteredHint": "输入你注册时使用的电子邮箱。",
			"loginBtnLogin": "进入",
			"loginMessageSuccessRegister": "您已成功注册",
			"loginMessageSuccessLogin": "您已成功登陆",
			"loginSuccessEmailText": "__username__，感谢您注册艺术挑战！<BR>现在你可以参加比赛，并保存你的游戏的统计数据。如有任何疑问请联系我们info@artchallenge.ru。如果您要追逐文化世界的消息，在我们的社交网络留言：<br> VKontakte等：http://vk.com/art.challenge <br> Facebook的：http://facebook.com/artchallenge.ru <br><br>真诚的，艺术挑战赛团队<br>鲁本和安娜。",
			"loginMessageErrorEmail": "输入正确的电子邮箱",
			"loginMessageError": "输入你的用户名和正确的电子邮箱",
			"loginMessageErrorDuplicate": "注册错误：此电子邮箱已存在。",
			"loginMessageErrorForbiddenName": "注册错误：此用户名已存在。",
			"loginMessageErrorServer": "注册错误：服务器不可用，请稍后再试",
      "errorOffline": "无网络连接",
      "swipeCollections": "选择游戏",
      "swipePictures": "打开画册",
      "yourPlace": "您在 __place__ 地方 ",
      "highQualityPictures": "高质量",
      "highQualityPicturesDesc": "从互联网下载高质量的图片",
      "picturesInRow": "依次",
      "reportError": "发现错误？",
      "reportEmail": "一定要告诉我们 report@artchallenge.ru",
      "subscribeNoSpam": "没有垃圾邮件。仅仅是来自艺术世界的好消息。",
      "about": "关于游戏",
      "aboutSponsors": "这要感谢亲爱的朋友们的支持下，鲁本·巴巴耶夫和安东·普洛特金创建了艺术挑战：",
      "gameVersion": "游戏版本",
      "exit": "退出"

		},
		"message": {
			"right": "正确",
			"right-desc": "你猜 __count__ 图片",
			"wrong": "错误！",
			"wrong-desc": "这样",
			"years": "年龄",
			"nationality": "民族",
			"genre": "流派",
			"learn-more": "了解更多",
			"winner": "祝贺你!",
			"winner-desc": "收集 <strong>__setName__</strong> 通过!",
			"winner-desc-old": "你对艺术领域非常擅长，十道题全部正确－打败了82%的玩家！",
			"share": "在社交网络分享你胜利的消息：",
      "winnerMobile": "你很擅长收集",
      "shareOrTournament": "告诉你朋友胜利的消息并参加最长回答正确的系列比赛：",
      "shareWithFriends": "告诉朋友们",
      "playTournament": "比赛",
      "loading": "载入中",
      "closeWinTitle": "开始小游戏",
      "closeWinMessage": "您想关闭这个窗口，开始新游戏吗？"
		},
		"badPhrases": {
			"1": "是的，你疯了？",
			"2": "你不感到羞愧吗？",
			"3": "你生病了？",
			"4": "胡说什么！",
			"5": "自我教育！",
			"6": "你怎么能这样？",
			"7": "不，不，不！",
			"8": "反省！",
			"9": "思考一下？",
			"10": "什么鬼？！",
			"11": "没文化！",
			"12": "上帝保佑！"
		},
		"goodPhrases": {
			"1": "回答正确！",
			"2": "正确！",
			"3": "正确！",
			"4": "非常棒！",
			"5": "太棒了！",
			"6": "超级棒！",
			"7": "棒！",
			"8": "完全正确！",
			"9": "十分正确！",
			"10": "准确！",
			"11": "对的！",
			"12": "准确！",
			"13": "对的！",
			"14": "奇妙的！",
			"15": "完美！",
			"16": "闪亮的！",
			"17": "赞美！",
			"18": "赞美的！",
			"19": "惊人的！",
			"20": "准确！"
		},
		"shares": {
			"title": "女士们和先生们，我很擅长艺术！",
			"description": "尝试猜想十位画家，和我们进行比赛！",
			"caption": "艺术挑战－著名艺术家的问答题。"
		},
		"footer": {
			"created": "网站创立",
			"ruben": "鲁本",
			"ruben-full": "鲁本·巴巴耶夫",
			"and": "和",
			"anna": "安东",
			"anna-full": "安东·普洛特金",
			"year": "在2014年",
			"vk": "VKontakte",
			"other-projects": "我们其他的计划"
		},
		"painters": {
			"1": "阿梅代奥·莫迪利亚尼",
			"2": "亨利莱巴斯克",
			"3": "库茵芝",
			"4": "瓦西里·康定斯基",
			"5": "瓦西里·苏里科夫",
			"6": "维克多·鲍里索夫",
			"7": "迭戈·里维拉",
			"8": "伊万·希什金",
			"9": "克劳德·莫奈",
			"10": "康斯坦丁 尤恩",
			"11": "尼古拉斯·罗瑞克",
			"12": "奥列斯特•基普连斯基",
			"13": "彼得罗夫·沃特金·库兹玛",
			"14": "勒内·马格利特",
			"15": "萨尔瓦多•达利",
			"16": "谢尔盖·维诺格拉多夫",
			"17": "爱德华·马奈",
			"18": "安德鲁·惠氏",
			"19": "安德烈·鲁布廖夫",
			"20": "维克多·瓦斯涅佐夫",
			"21": "文森特·威廉·梵高",
			"22": "克林姆",
			"23": "伊凡·康斯坦丁诺维奇·艾瓦佐夫斯基",
			"24": "波希",
			"25": "伊利亚 列宾",
			"26": "卡济米尔·谢韦里诺维奇·马列维奇",
			"27": "米哈伊尔·亚里山大罗维奇·弗鲁贝尔",
			"28": "毕加索",
			"29": "彼得·保罗·鲁本斯",
			"30": "皮埃尔 - 奥古斯特·雷诺阿",
			"31": "塞奥法尼斯 希腊",
			"32": "弗朗西斯科 戈雅",
			"33": "弗里达·卡罗",
			"34": "格列柯",
			"35": "杜勒",
			"36": "阿尔弗雷德·西斯莱",
			"37": "鲍里斯·克斯托依列夫",
			"38": "卡尔·布留洛夫",
			"39": "彼得·勃鲁盖尔",
			"40": "卡尔·布留洛夫",
			"41": "乔托迪邦多",
			"42": "波提切利",
			"43": "卡拉瓦乔",
			"44": "欣内妲 叶夫根尼耶夫娜 舍薇布娅卡娃",
			"45": "达芬奇",
			"46": "维拉斯奎兹",
			"47": "瓦西里 韦列夏金",
			"48": "艾萨克·列维坦",
			"49": "亨利·马蒂斯",
			"50": "扬·凡·艾克",
			"51": "约翰·沃特豪斯",
			"52": "埃贡·席勒",
			"53": "埃德加·德加",
			"54": "伦勃朗",
			"55": "提齐安诺·维伽略",
			"56": "阿方斯·慕夏",
			"57": "亨利·图卢兹 - 劳特累克",
			"58": "库尔贝",
			"59": "但丁 加百列 罗塞蒂",
			"60": "约翰·萨金特",
			"61": "毕沙罗",
			"62": "威廉·特纳",
			"63": "爱德华·蒙克",
			"64": "安托 万华托",
			"65": "威廉·阿道夫·布格罗",
			"66": "约翰·康斯特布尔",
			"67": "约翰·埃弗里特 米勒",
			"68": "彼得·德·霍赫",
			"69": "塞尚",
			"70": "西奥多·杰利柯",
			"71": "托马斯·庚斯博罗",
			"72": "威廉·布莱克",
			"73": "欧仁·德拉克罗瓦",
			"74": "扬·弗美尔",
			"75": "亨利卢梭",
			"76": "卢卡·波罗维科·鲍罗维柯夫斯基",
			"77": "乔治·修拉",
			"78": "卢西安·弗洛伊德",
			"79": "保罗·克利",
			"80": "蒙德里安",
			"81": "帕维尔 菲洛诺夫",
			"82": "米罗",
			"83": "安迪·沃霍尔",
			"84": "瓦伦丁·谢罗夫",
			"85": "阿列克谢 哈尔诺夫",
			"86": "瓦西里 特罗比林",
			"87": "弗拉·安杰利科",
			"88": "爱德华·伯恩 - 琼",
			"89": "马丁·施恩告尔",
			"90": "罗希尔·范德魏登",
			"91": "乔凡尼-保罗",
			"92": "汉斯·巴尔东·格里恩",
			"93": "古斯塔夫·莫罗",
			"94": "保罗·高更",
			"95": "拉斐尔",
			"96": "保罗·西涅克",
			"97": "尼古拉斯·普桑",
			"98": "汉斯·荷尔拜因",
			"99": "威廉·霍尔曼·亨特",
			"100": "阿尔布雷希 阿尔特多费尔",
			"101": "安托内罗·达·梅西那",
			"102": "亚瑟·休斯",
			"103": "亚历山大·尼古拉·耐瓦",
			"104": "汉斯·梅姆林",
			"105": "亚历山大· 杰伊涅卡",
			"106": "乔尔乔",
			"107": "亚历山大·伊万诺夫",
			"108": "柯雷吉欧",
			"109": "德米特里·列维茨基",
			"110": "卢卡斯·范·莱顿",
			"111": "卢卡斯·克拉纳赫",
			"112": "米开朗基罗",
			"113": "尼古拉·戈",
			"114": "罗伯特·坎",
			"115": "陀罗可托夫",
			"116": "罗克韦尔肯特",
			"117": "马里洛斯史良",
			"118": "杰克逊·波洛克"
		},
		"nation": {
			"Russian": "俄罗斯人",
			"Armenian": "亚美尼亚人",
			"Italian": "意大利人",
			"French": "法国人",
			"Mexican": "墨西哥人",
			"Belgian": "比利时人",
			"Spanish": "西班牙人",
			"American": "美国人",
			"Dutch": "荷兰人",
			"Austrian": "奥地利人",
			"Flemish": "佛兰芒人",
			"German": "德国人",
			"British": "英国人",
			"Jewish": "犹太人",
			"Belarusian": "白俄罗斯人",
			"Czech": "捷克人",
			"Greek": "希腊人",
			"Norwegian": "挪威人",
			"Ukrainian": "乌克兰人",
			"Swiss": "瑞典人"
		},
		"genre": {
			"Romanticism": "浪漫主义",
			"Expressionism": "表现主义",
			"Impressionism": "印象派",
			"Realism": "现实主义",
			"Abstractionism": "抽象主义",
			"Symbolism": "象征主义",
			"Muralism": "互惠共生{现象}",
			"Social Realism": "社会现实主义",
			"Surrealism": "超现实主义",
			"Byzantine Art": "拜占庭艺术",
			"Post-Impressionism": "后印象派",
			"Art Nouveau": "新艺术运动",
			"Northern Renaissance": "北方文艺复兴",
			"Suprematism": "至上主义",
			"Cubism": "立体主义",
			"Baroque": "巴洛克",
			"Iconography": "圣像画术",
			"Primitivism": "原始主义",
			"Mannerism": "风格主义",
			"Neoclassicism": "新古典主义",
			"Proto Renaissance": "原文艺复兴",
			"Early Renaissance": "早期文艺复兴",
			"Art Deco": "装饰艺术",
			"High Renaissance": "高级文艺复兴",
			"Aestheticism": "唯美主义",
			"Analytical Realism": "分析现实主义",
			"Neoplasticism": "荷兰风格派运动",
			"Rococo": "洛可可",
			"Pop Art": "流行艺术",
			"Socialist Realism": "社会主义现实主义",
			"Academic Art": "学院派",
			"Abstract Expressionism": "抽象表现主义"
		},
		"sets": {
			"basicSet": "著名艺术家",
			"basicSet-desc": "著名艺术家的作品集",
			"basicSet-count": "50位艺术家，8450幅绘画",
			"renaissanceSet": "文艺复兴时期",
			"renaissanceSet-desc": "印象派和后印象派",
			"renaissanceSet-count": "21位艺术家和2783幅绘画",
			"impressionismSet" : "印象派和后印象派",
			"impressionismSet-desc" : "印象派和后印象派的作品",
			"impressionismSet-count": "18位艺术家，4231幅绘画",
			"realismSet": "现实主义的艺术家",
			"realismSet-desc": "现实主义绘画艺术家作品集",
			"realismSet-count": "12位艺术家，2083幅绘画",
			"russianSet": "俄罗斯艺术家",
			"russianSet-desc": "所有的时期和不同流派的绘画的",
			"russianSet-count": "33位艺术家，5140幅绘画",
			"frenchSet": "法国艺术家",
			"frenchSet-desc": "法国艺术家收藏",
			"frenchSet-count": "22位艺术家，3758幅绘画",
			"allSet": "全集",
			"allSet-desc": "所有的艺术家的作品加入游戏——对于有经验的玩家",
			"allSet-count": "118位艺术家，17695幅绘画"
		}
	}];
	
	var exec = require('child_process').exec;


	en = en[0];
	en._id = String("en");

	de = de[0];
	de._id = String("de");

	it = it[0];
	it._id = String("it");
	
	fr = fr[0];
	fr._id = String("fr");
	
	zh = zh[0];
	zh._id = String("zh");
	
	es = es[0];
	es._id = String("es");
	
	
	
	




		var cmd = "curl -H 'Content-Type: application/json' -X POST http://178.62.133.139:5997/lang/ -d '" + JSON.stringify(es).replace(/'/g, "") + "'";

		exec(cmd, function(error, stdout, stderr) {
			// console.log(cmd)
			console.log(stdout);
		});	
			
	